### ISSUE TITLE
Disable DVR

### ISSUE THREAD

**Issue by shaharmor** [jwplayer/jwplayer#1016]
Hi,

how can i disable DVR even for streams that jwplayer can use DVR with?

**Comment by robwalch** [comment]
Hi @shaharmor,

Do you want to disable it from the player's API, or from within your custom provider? When you say disable, I assume you mean show the Live controls rather than the DVR controls, correct?

There is not way to do this from our API (other than hiding all controls and providing your own). From the provider, if you output the duration as Infinity then the stream will appear as a "Live" stream. If you have control of the stream itself, and you could configure it to only contain less than 1-2 minutes of content then the player would treat it as "Live".

**Comment by shaharmor** [comment]
I just want to hide the DVR controls, but i don't want to change the stream because for some users i do want to show DVR.

Will it be possible to add a `dvr: false` property to the player initialization?

**Comment by robwalch** [comment]
I don't think we'll get to adding that option anytime soon. You can hide and turn off controls with `.setControls(false)`:

```js
jwplayer().once('time', function(e) {
    this.setControls(e.duration <= -120);
});
```
