### ISSUE TITLE
[7.3.0-beta] Closed captions are not displaying on iOS

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#1060]
Hi,
 i experienced problems while implementing closed captions. They works well on almost every platform. Unfortunately there is an issue on iOS (safari) - captions are not displaying on fullscreen.
I did some debugging and found that if VAST ads are not provided then player shows captions properly. When ads configuration is set then tag `<track>` is not rendered in player.

You can check example here:
http://stage-cdn.svp.schibsted.io/player/vtt-captions/

**Comment by esboyd** [comment]
Thanks for submitting this @artur-michalak. Can you please reach out to me here - eric@jwplayer.com. I really like the content in your example and want to ask you some other questions not related to this open issue.

**Comment by robwalch** [comment]
Just finished up a fix for this #1061

**Comment by robwalch** [comment]
@artur-michalak please try with v7.3.1 http://ssl.p.jwpcdn.com/player/v/7.3.1/jwplayer.js

Thanks!

**Comment by artur-michalak** [comment]
Thanks for quick fix. It works well now, however.. i do have one more question.
When i'm selecting languages i'm getting views as below (Unknown CC - see attached screenshots). Am i doing something wrong? Example is the same http://stage-cdn.svp.schibsted.io/player/vtt-captions/
![thumb_img_0147_1024](https://cloud.githubusercontent.com/assets/2443904/13214181/627ee3c2-d94e-11e5-81bc-4be2c1bd9cfb.jpg)
![thumb_img_0148_1024](https://cloud.githubusercontent.com/assets/2443904/13214182/6281a86e-d94e-11e5-90a0-56c457088fa6.jpg)

**Comment by robwalch** [comment]
Hi @artur-michalak,

The "Unknown CC" track comes from Safari when loading HLS streams. A captions textTrack is always present by default. Apple describes the issue here:

https://developer.apple.com/library/ios/qa/qa1801/_index.html

Apparently you can disable the default caption menu by including `CLOSED-CAPTIONS=NONE` in each `EXT-X-STREAM-INF` of the master playlist.

We did not mimic this behavior in Flash (in Flash we add the track once 608 captions are parsed). For HTML5 playback in Safari, we're sticking with the browser's default behavior.

**Comment by artur-michalak** [comment]
Thank you :+1:  I think you answer would be worth to mention in official docs :)

**Comment by esboyd** [comment]
@androoP let's get this added to our 608 and CC docs. Thanks @artur-michalak

**Comment by aimankazi** [comment]
Hello friends,
I am working on jw player since version 6.12. im able to fetch captions from live stream using jw player on desktop. On iOS i can see captions in the native video player but not using jw player. 
IS THERE A WAY TO GET CAPTION OUT OF THE LIVE STREAM ON iOS AND PRINT THE SAME ON THE HTML PAGE. IF YES THEN PLEASE PROVIDE ME WITH A LINK.

**Comment by robwalch** [comment]
@aimankazi we've implemented support for TextTracks in 7.3. Updating to 7.3 will make the captions menu available in iOS when not in full screen. Our API does not support extracting captions content. You can do that with JavaScript by accessing the video tags textTracks. Here's a demo, you can add your own HLS stream with captions and hit 'Add Source'. The page will print out all the track info:

http://demo.jwplayer.com/tracks-and-ranges/

**Comment by aimankazi** [comment]
@robwalch :  Thanks alot. im able to get the caption value and fetch it as textTracks on iOS. But its not coming on android. how its possible to get the same value on android device
