### ISSUE TITLE
Cannot get JW7 from git repo

### ISSUE THREAD

**Issue by TheNemus** [jwplayer/jwplayer#1069]
### Expected Behavior

`bower install jwplayer --save`

bower.json:
`"jwplayer": "~7.3.xxxx"`

### Actual Behavior

`bower install jwplayer --save`

bower.json:
`"jwplayer": "~6.12.xxxx"`

### Steps to reproduce

Just install the dependency with bower

if I force the update I get this
```

C:\Users\.xxxxx\>bower update jwplayer --save
bower cached        git://github.com/sathyapulse/jwplayer.git#6.12.4956
bower validate      6.12.4956 against git://github.com/sathyapulse/jwplayer.git#
~6.12.4956
```

### Environment

Windows 8
Node 4.1.1
bower 1.6.3

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Hi @TheNemus,

That bower package is not maintained by us. Contact @sathyapulse for help with that.

Our commercial library extends this project. Because of this nature we do not publish npm or bower packages of our library. It can be downloaded from your account [here] (https://dashboard.jwplayer.com/#/players/downloads). Or here using our CDN:

//ssl.p.jwpcdn.com/player/v/7.3.2/jwplayer.js

**Comment by TheNemus** [comment]
thank you
