### ISSUE TITLE
ID3 tag parsing in Edge includes null terminator character

### ISSUE THREAD

**Issue by IsaacSchemm** [jwplayer/jwplayer#1101]
### Expected Behavior

A cue point with hex data 486900 should be interpreted as "Hi"

### Actual Behavior

In Edge, using HTML5 to play HLS, it is interpreted as "Hi\0"

### Steps to reproduce

1. Use JW Player in Edge to play an HLS stream with timed metadata, like the one I linked to in pull request 1046
2. Play in both Flash and HTML5 mode - Flash mode will not have a \0 character in the string; HTML5 version will

### Environment

- *Windows 10*
- *Edge 25.10586.0.0*

**Comment by IsaacSchemm** [comment]
I haven't checked, but this may have been resolved by 834fa90d64a668d9b7191ae0d97b12bf65065cfe, at least for UTF-8.

**Comment by robwalch** [comment]
Thanks @IsaacSchemm! If you know where we can get a sample with UTF16 encoded metadata let us know. This issue should be fixed since out last two beta releases (7.4.0-beta.3+).

Not only are we skipping those bytes in the UT8 method, we're also incrementing the read position which may have caused additional bytes to be left over in subsequently parsed ID3 fields for UTF8 and UTF16.

**Comment by IsaacSchemm** [comment]
This one has both UTF-8 and UTF-16 metadata:
http://www.lakora.us/media/playlist.m3u8

**Comment by robwalch** [comment]
@pajong can you give an update on this issue?

**Comment by pajong** [comment]
The issue with UTF-16 has been fixed with: https://github.com/jwplayer/jwplayer/pull/1158
The issue with UTF-8 is fixed in the commit that @IsaacSchemm has mentioned.
Please feel free to re-open the ticket if you see any further problems.
