### ISSUE TITLE
Please publish and maintain an official npm module

### ISSUE THREAD

**Issue by cowboy** [jwplayer/jwplayer#1110]
I see this, but it's not completely up-to-date with your latest source:

https://github.com/bianjp/jwplayer

It would be really helpful for the community and developers if you could maintain an npm module that was at parity with your source.

Thanks!

**Comment by robwalch** [comment]
Hi @cowboy,

We've had similar requests to maintain a bower package - #1069. The issue is our commercial library which is the player you get from our CDN (//ssl.p.jwpcdn.com/player/v/7.3.6/jwplayer.js) and [your user account dashboard](https://dashboard.jwplayer.com), extends this project, and is not open-source. Because of this, we do not publish npm or bower packages of our library.

**Comment by jonhermansen** [comment]
@robwalch Would you consider another model, something like what @FortAwesome is doing with Font Awesome Pro? They have a private NPM registry available behind a paywall. Paying users can authenticate with an NPM_TOKEN.

**Comment by robwalch** [comment]
Hi @jonhermansen thank you for the suggestion.

Providing access to a private registry is something we might consider. I would be more likely to push for the commercial builds to be available publicly on npm with tools in the package that help users register and retrieve their JW license key.
