### ISSUE TITLE
Can't build jwplayer on windows 10

### ISSUE THREAD

**Issue by jamejiraju** [jwplayer/jwplayer#1135]
Hi,

I have already installed node.js and JAVA and Adobe air SDK. I also installed air SDK by using npm. and when I use npm install in my jwplayer directory I got this error:

![error_install](https://cloud.githubusercontent.com/assets/18496193/14579951/54294682-03e7-11e6-83c4-0f733cc78362.JPG)

Please help me to solve that.
Thanks,

**Comment by robwalch** [comment]
The error message states that bower failed because git is not installed or in your PATH.

The Windows installer for git can be found here https://git-scm.com/downloads

Bower's troubleshooting wiki page describes how to install the requirements on Windows https://github.com/bower/bower/wiki/Troubleshooting
