### ISSUE TITLE
Play button requires 3 clicks to start video

### ISSUE THREAD

**Issue by waraulin** [jwplayer/jwplayer#1173]
### Expected Behavior

Clicking the play button on the .jpeg overlay on the video should immediately begin playing the video.

### Actual Behavior

Clicking the play button on the .jpeg overlay hides the .jpeg and loads the video player. Then, another play button appears in the center of the video container with a black-opaque overlay behind it. Clicking the second play button clears the black-opaque overlay and play button and pauses the video. Finally, clicking the third play button (the standard play button in the jwplayer control bar) will begin playing the video.

### Steps to reproduce

1. Visit https://www.omgyes.com/en/how-it-works
2. Click "Read more about the research +" to display the drop-down content section containing the affected video
![hiwexpansion](https://cloud.githubusercontent.com/assets/6526153/14970239/2dda072c-107c-11e6-904f-9d55fc184866.jpg)

3. Click the play buttons on the video container and observe actions required to start video

### Environment

- Macbook Air
- OS X Yosemite (10.10.3)
- JW Player version 7.3.2 URL: https://www.omgyes.com/en/how-it-works
- While this issue has been experienced across various devices and browsers, currently while trying to reproduce it, the issue is present _only_ in Google Chrome and _not_ in Safari on Macbook Air. The issue can be reproduced without fail on Windows 7 Desktop in Chrome (v50).

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by waxidiotic** [comment]
@waraulin - This behavior is caused by Chrome's throttling of Flash content under a certain size. This is a limitation imposed by Chrome and is out of our control.

I did notice that you are embedding a RTMP stream. I would recommend checking into whether or not you can serve that stream as HLS, as our player will be able to render HLS streams without the use of Flash in Chrome when 7.4.0 is released in a few weeks. You can read more about this functionality [on our developer site](https://developer.jwplayer.com/jw-player/docs/developer-guide/beta/html5_hls_beta/). 

I've also linked to some blog posts that we've written regarding Chrome's throttling of Flash content below.

[JW Player Blog - How Chrome Power Saving Will Affect JW Player](https://www.jwplayer.com/blog/chrome-power-saving/)
[JW Player Blog - Flash Throttling: Improving the Experience](https://www.jwplayer.com/blog/flash-throttling)

**Comment by waraulin** [comment]
@waxidiotic, thank you!! We've been trying to track this one down for several months but to no avail, this info is very helpful! Closing ticket.
