### ISSUE TITLE
HLS playpack fails on 7.4.0 in Vivaldi, possibly others

### ISSUE THREAD

**Issue by IsaacSchemm** [jwplayer/jwplayer#1180]
### Expected Behavior

HLS playback should use HTML5 in Chromium-based browsers when possible but fall back gracefully to Flash.

### Actual Behavior

In some Chromium-based browsers, JW Player throws an error when trying to play HLS in HTML5 and does not fall back to Flash, instead showing the message "TypeError: Cannot read property 'push' of undefined"

### Steps to reproduce

1. Embed JW Player on a page and point it to an HLS stream (on a server where cross-domain access is allowed)
2. Open the page in Vivaldi

### Environment

- Windows 10 (64-bit)
- Vivaldi 1.1.453.45 (32-bit)
- JW Player 7.4.0

The same error occurs in the first AOL Desktop 11 sneak preview (http://beta.aol.com/projects/desktop/windows), so I don't think it's specific to Vivaldi.

I did some investigating in the developer tools, and at one point in Vivaldi the error "Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('audio/aac') is unsupported." is thrown and then caught. This does not seem to happen in Chrome/

**Comment by johnBartos** [comment]
We don't officially support Vivaldi (sorry!). Sounds like it lacks support for Media Source Extensions. Right now we're doing a User Agent check to determine if the browser can use our HLS plugin - we'll put in a ticket to make the check more robust.

**Comment by fdambrosio** [comment]
we ha a similar problem on Opera 37.0.2178.43 / Mac OS X 10.11.5 64-bit / Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36 OPR/37.0.2178.43 
An HLS mp4 ondemand stream video return "Error playing file: source not supported"

**Comment by neilRGS** [comment]
Hi.
Can you tell me which browsers your HLS plugin will work with please?
I have to play to a flash-free environment and so far, only MS Edge will comply.  All other browsers I have attempted with, try to use flash. Bearing in mind that flash is being phased out by Chrome (and possibly/probably others), I feel it is imperative that the render should fall back to flash, after trying other modes.
Another reason that I need to force html5/hls is because autostart will not work when playing through an iframe (as happens often in SCORM applications) - an overlay is applied to the flash player, forcing the user to click to pause, then click to play the video.  This behaviour makes for poor UX, and therefore a lot of nagging from our clients to try and get it fixed.

Thanks in advance for your advice.

Neil.

**Comment by johnBartos** [comment]
As of now (7.4.3) the only browsers that support HLS with HTML5 is Chrome, Safari, and mobile browsers. You need to set `hlshtml=true` in the config to make it work. Support for FF and IE11 is coming in 7.5.0

https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/#rendering-and-loading

**Comment by neilRGS** [comment]
Ok, thanks John.
I'll keep an eye out for 7.5.0.  Support for the other browsers will be a massive help.

Many thanks,

Neil.

**Comment by johnBartos** [comment]
@neilRGS No problem!
