### ISSUE TITLE
JW7 : Jumping/Skipping to an unbuffered scene does not work in Flash Pseudostreaming

### ISSUE THREAD

**Issue by einthusan** [jwplayer/jwplayer#1250]
### Expected Behavior

When in Flash mode using NGINX for pseudo streaming and jumping/skipping to a scene that is yet not buffered, we expect it to load that scene and update the time display + seek bar accordingly.

### Actual Behavior

In Flash mode (our primary mode) with proper nginx pseudo streaming query parameters being used (startparam) we are able to jump/skip to a different scene in the video. Although the video does start playing from the new jump point, the seek bar + time display shows as if the video is starting from 0:00 duration.

NOTE: if we jump to a **buffered** portion of the video (refresh the page and wait for some part of it to load), this problem is not there.

### Steps to reproduce

1. Go to https://support.jwplayer.com/customer/en/portal/articles/1430518-jw6-pseudo-streaming-in-flash
Even though it says JW6, if you right click the player and see the version, it is JW 7.4.3

2. Jump to a random scene that is yet to be buffered.. towards the end is better. Make sure you are in Flash mode.

### Environment

-  Desktop (Windows and Mac)
- (Windows 10 & OSX Yosemite)
- JW Player 7.4.3 (latest as of now)

**Comment by johnBartos** [comment]
Hey @einthusan, thanks for the report + test page. We'll take a look and get back to you soon

**Comment by johnBartos** [comment]
What browser are you using?

**Comment by johnBartos** [comment]
@einthusan We don't support psuedostreaming anymore - marking it as wontfix. I believe that version 6 was the last supported version

**Comment by einthusan** [comment]
We've been paying for JW Ads for several years now and now we are forced to fork a version and make the changes ourself to support pseudo streaming. That is quite hectic. There is no open source alternative to pseudo streaming. This descion seems like it was on purpose to move everyone off pseudo streaming but that's the most easiest technology to write support for in a video player. I am shocked to see this reply. When was it stated that support would be dropped, can you point out a publicly available announcement? Even if you can, it shows that JW Player isn't open source as it was when it was originally founded. And we were there 5 years ago to support the development of the video player!

**Comment by einthusan** [comment]
Here is a rep from JW Player saying support will be added in 7.x!! https://support.jwplayer.com/customer/portal/questions/13084718-pseudo-streaming-support-dropped-in-flash-rendering-mode

**Comment by esboyd** [comment]
@einthusan we removed pseudostreaming because it relies on Flash and is not a viable streaming technology. As a paying customer you have access to HLS and MPEG-DASH streaming playback, which are supported everywhere, including mobile devices. Also as a Ads customer you have expanded hosting and streaming with us in your account dashboard. We automatically transcode and stream all of your videos via HLS, making it extremely convenient for you to an optimal experience for your viewers. 

Also here is the notes on where we removed support for this functionality. See section on removed features.

https://support.jwplayer.com/customer/portal/articles/2037989

**Comment by einthusan** [comment]
@esboyd almost all video ad inventory still relies on Flash. If you removed pseudo-streaming because it relies on Flash, then why didn't just remove Flash itself? Why are you still supporting a Flash fall-back? How are we suppose to properly use Flash Ads when we pay for JW Player Ads license? We stream over 4000 TB (yes, TB!) of data a month. Please, using your JW hosting and streaming services (which the sell is for) would be ridiculously expensive compared to our current solution.

**Comment by esboyd** [comment]
Video ads do indeed still rely on flash, which is why you can set the primary of the player to render in and use flash. All I am saying is that you should switch to a modern streaming protocol, like HLS or DASH, which would end up saving you on monthly streaming costs, independent on which streaming provider you use. We support HLS in both Flash and HTML5, you have access to this functionality in the version of the player that you are currently paying for. 

https://support.jwplayer.com/customer/portal/articles/1430189-about-hls-streaming

**Comment by einthusan** [comment]
But please point me out to an open source server plugin for HLS. Nginx (which we currently use) requires a paid platform. Although we donate to these open source code bases, we do see a pattern that all "open-sourced" code bases are now offering a "paid" version that supports new technology like HLS.. But has stopped maintaining technologies that they do not profit from, like pseudo streaming. With your knowledge and expertise in the video streaming industry, please do point out an open-source HLS server or plugin for a server. If your unable to do so, at least guide us to how we can add our own support for pseudo-streaming while legally abiding the licensing terms for JW Ads Edition of the player.
