### ISSUE TITLE
Increase decimal scale of getPosition

### ISSUE THREAD

**Issue by maxstoller** [jwplayer/jwplayer#1325]
It seems `getPosition` returns a number number with 1 decimal place. Would it be possibly to modify this function to return a number rounded to two decimal places instead?

**Comment by johnBartos** [comment]
@maxstoller We don't truncate the position, it's accurate to 6 places when applicable. I believe that 0's are automatically dropped though (so 14.000000 -> 14). What's your use case?

**Comment by maxstoller** [comment]
Hi @johnBartos -- Thanks for the quick response. We're syncing playback of two videos. Here's a demo of getPosition returning 1 decimal places. Watch the JS console. https://jwplayer-demo.herokuapp.com/

**Comment by johnBartos** [comment]
Ah, its because it's an RTMP stream. We're cutting it to the tenth there but it can easily be changed - do you want to contribute and submit a PR for it?

Here's the line to change: https://github.com/jwplayer/jwplayer/blob/master/src/flash/com/longtailvideo/jwplayer/media/RTMPMediaProvider.as#L428

And here's what it should look like:
https://github.com/jwplayer/jwplayer/blob/master/src/flash/com/longtailvideo/jwplayer/media/VideoMediaProvider.as#L255

**Comment by maxstoller** [comment]
Done, thanks @johnBartos. I increased it to 5 decimal places, but I can cut it to 3 if needed.
