### ISSUE TITLE
Smart TV support

### ISSUE THREAD

**Issue by einthusan** [jwplayer/jwplayer#1331]
Just a general issue regarding existing support for Smart TVs like Samsung and LG and if there currently isn't any support, what is the plan or roadmap regarding this. I've tried searching the code base and existing issues but couldn't not find anything related to this. I know version 6.x had no issues when using pseudo streaming but now with 7.x and HLS, I think the native support from the Smart TV isn't there anymore, hence the creation of this issue.

**Comment by esboyd** [comment]
pseudo streaming would not work on Smart TVs because they lack support for Flash plugins. Though we do not explicitly test Smart TVs, if you are using the native browsers and they support HTML5. 

Do you have an explicit page or app you are trying to test? We support TV casting through chromecast and have an open source apple-tv app.

https://github.com/jwplayer/appletv

**Comment by einthusan** [comment]
@esboyd Let me do a bit more research on this. I also assume no plans for testing Smart TVs has been put in place yet?

**Comment by johnBartos** [comment]
@einthusan I don't believe so, closing this out since it's not an issue
