### ISSUE TITLE
Preload none on IE

### ISSUE THREAD

**Issue by Bruno-Tvtrip** [jwplayer/jwplayer#1463]
### Expected Behavior

The standard video tag with a poster and a preload attribute set to none on IE doesn't preload the video. But JWPlayer with the same settings on IE does the preload of the video. Could you make that JWPlayer respects the behavior of the browser ?
### Actual Behavior

JWPlayer with a poster and a preload setting set to none on IE starts the preload of the video
### Steps to reproduce
1. Setup a JWPlayer with a file(classic MP4) and an image (JPEG)
2. Add the setting's player preload to 'none'
3. Test on IE 11 -> you can see on the network panel all the MP4 calls without playback
### Environment
- Window 7
- IE 11
- JWPlayer 7.6.1 (JWPlayer 7)

Thank you!

**Comment by johnBartos** [comment]
@Bruno-Tvtrip We've been aware of this issue but it's very low priority. Is this a serious problem for your site?

**Comment by Bruno-Tvtrip** [comment]
On my websites, I have 2-3% of errors to fetch video files. On an error, I retry to get the file and retry to play it. But the preload mechanism triggers the same error ("Error loading media: File could not be played") and the retry is done with a play. So sometimes a player on IE can autoplay a video with any user action.

To complete the issue:
Actually, on IE when you create the video tag via JS with a preload attribute set to 'none', the video is loaded. There is a difference between video tag created with JS and built in HTML (thank IE).

**Comment by robwalch** [comment]
Setting the preload property in addition to the attribute might do the trick.

`videoElement.preload = 'none'`

**Comment by robwalch** [comment]
This is a browser bug and there is no workaround in the player code that can fix it.

The same issue was reported to video.js:
https://github.com/videojs/video.js/issues/3879

Here's the bug in Microsoft's tracker:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8982801/

You can setup jwplayer using a div with video tag in it:
```html
<div id="player">
    <video preload="none"></video>
</div>
```
```js
jwplayer('player').setup({ file: 'video.mp4' })
```

But from my tests preloading is always performed in IE 11 on Windows 10 regardless of whether or not you use static html or javascript to create the video element.

Since you have a very specific use case for your application, and you're using our API it sounds like you could work around playback starting when you get an error before playback has started by simply setting up the player again with a different video or calling load and stop.
