### ISSUE TITLE
Cannot load M3U8: Unable to fetch HTTP resource over HTTPS

### ISSUE THREAD

**Issue by moinmail** [jwplayer/jwplayer#1581]
Video player should work fine with .m3u8 videos without flash player over https from http video url.

In jwplayer version 7.6.1, there was a massage in console for mixed content for .m3u8 served from http on https url. crossdomain.xml is already setup for the url from Akamai server.

I just tried updating from 7.6.1 to 7.8.2 and i noticed instead of showing warning (as in 7.6.1) in console.log the player is stop playing with hlshtml:true and primary: "html5" in Google Chrome and Mozilla Firefox. Videos are serving from Akamai server and crossdomain file is also present.

I am checking with Windows 7 with Chrome version :55.0.2883.75 and Firefox version: 50.0.2

Sorry I don't have un-skinned URL for the player to show the issue.

**Comment by johnBartos** [comment]
We've had similar reports and are looking into it. Can you paste your config?

**Comment by bramus** [comment]
This is due to [Mixed Content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content): you cannot load an HTTP resource from an HTTPS resource. Chrome (and other browsers that implement this security feature) block these kinds of requests.

_(Note: During some testing a while I've noticed one exception though: a `<video>` element with an HTTP `.mp4` resource will load just fine. I guess it's because it's a binary format or something like that.)_

**Comment by davidcodesido** [comment]
Any progress? We moved from jwplayer 6.X to 7.X and we're facing the same issue. With the recent announcements of flash being finally deprecated we are planning to move to html5 player only but since our video sources are HTTP and the web is HTTPS we are facing this issue. Changing the video to HTTPS is not an option since it is a purchased CDN (and to be honest I don't think it makes sense at all to have video chunks over HTTPS) and moving our web to HTTP is an ugly hack since we have authentication and a shop.

**Comment by bramus** [comment]
@davidcodesido There is no other option than moving your video sources to HTTPS. This is a standardised security measurement built into browsers: when loading HTTP resources on an HTTPS enabled website, your browser – and not jwplayer to make things clear – will block loading it. Therefore this is something outside of the scope of jwplayer.

On a sidenote: Your CDN should be able to provide HTTPS rather cheap or even at no extra cost – [certainly in times where certificates are free and automated](https://letsencrypt.org/). Perhaps this type of issue – e.g. “Mixed Content” – will give you some leverage when talking with them. If still then your CDN cannot provide HTTPS, it's time to reconsider which CDN provider you're using to be honest.

**Comment by robwalch** [comment]
Closing. This is a mixed content issue. Our player cannot circumvent browser security.

**Comment by kaanozcan** [comment]
@moinmail It's been a while but have you tried hls-buffer? I am faced with the same issue so I am proxying the http resource. https://github.com/mafintosh/hls-buffer
