### ISSUE TITLE
Q: How does jwplayer handle HDCP for HTML5 Video?

### ISSUE THREAD

**Issue by pjdicke** [jwplayer/jwplayer#1716]
Gathering some information around a requirement and I need to know if the jwplayer downgrades to SD keys (if available), if the users setup doesn't support HDCP or if you display an error message or do something else?

Thanks

**Comment by pjdicke** [comment]
Ok, thanks. Keep me posted if you discover anything.

I have found that only a few groups are actually attempting to handle HDCP in some way, either by throwing an error (hasplayer.js) or actually downgrading to SD (Shaka player). The rest aren't doing anything.

Do you guys have any plans to support handling HDCP?

**Comment by robwalch** [comment]
We do not.

In Safari, the browser and operating system handle it (if there are HDCP restrictions on video it will render a black box when screen sharing).

Outside of that I haven't looked in to it and it is not on our product road map. What kind of JavaScript libraries are browsers exposing to handle HDCP?

Since we use Shaka player to play DASH streams, if you're video is in that format you'll get whatever support is there in shaka-player 2.0.1 (soon updating to 2.0.4).

**Comment by pjdicke** [comment]
Shaka actually downgrades to you regardless if your HDCP configuration is valid or not. You of course need to have SD steams available. They seem to be the only ones who are gracefully doing something.

w3 has started some chatter about having an API to do early detection but it's nothing available today. https://github.com/w3c/encrypted-media/issues/311

**Comment by robwalch** [comment]
That's not enough for us to start feature development. Interesting topic, but there is no logic for the player to get involved here.
