### ISSUE TITLE
Simplify ESLint rules

### ISSUE THREAD

**Issue by johnBartos** [jwplayer/jwplayer#1820]
The initial barrier for ESLinting existing files takes too much work to realistically complete. We should come up with a minimum set of rules to lower the barrier to linting.

**Comment by jthomerson** [comment]
As an outsider (but someone who uses and relies on JWPlayer) reading this, the idea is very concerning to me.

This sounds like "we have ugly code" and the only answer is "stop striving for better code". Where I work we've worked tirelessly the last year to create eslint rules that cover every little nitpicky thing that we've ever decided on as a team should be our standard (you can see our config [here](https://github.com/silvermine/eslint-config-silvermine)). And since those standards were always just in writing (enforced by hoping we manually caught them in code review) and now are being programmatically enforced, it's been a lot of work to get all our codebases up to those standards. But that didn't stop us from trying.

In the end, the effort is well worth it. We've actually fixed bugs in the process of bringing our coding standards up - bugs we didn't realize were there before. Many linting rules are done specifically to avoid certain types of errors. Others may be more stylistic, but having a consistent style itself helps avoid some errors.

To compare: if your codebase was a bridge and the inspector said "it's got a lot of rust and some really old bolts that are likely to fail, so I'm failing the inspection", would you just ask him to change the rules?

![](https://i.kinja-img.com/gawker-media/image/upload/s--edzp6ANO--/c_scale,f_auto,fl_progressive,q_80,w_800/19270dscwf5cpgif.gif)

Thanks for considering.

**Comment by johnBartos** [comment]
@jthomerson Honestly I'm with you on this one. I'm a fan of strict linters and opinionated styles and put in a lot of effort to resolve tech debt and drive standards. Having a clean codebase is important to me, not just because the code is prettier but because it's easier to work with. However, I believe what we're doing here is the right move because of the age (and lack of prior strong linting) of our codebase, which makes it extremely difficult to apply a huge ruleset up front.

This codebase is pretty old. Since [2014](https://github.com/jwplayer/jwplayer/commits/master/.jshintrc) we've been using JSHint to enforce style in this repo (and our closed-source repos too). At 22 lines total these rules are extremely basic. Since I've only been here since May 2016 I can only speculate, but we did give the proper diligence to our lint rules over the years - there was very little evolution. As we added features, we also added weeds, [mud](http://www.laputan.org/mud/), and clutter. We're a very small team (and it was even smaller in 2014) and work very hard to hit our product goals; we focus on "GSD" or "getting shit done". Tech debt and linting takes a backseat to the product.

When we began transitioning from JSHint to ESlint we forked our styleguide from [Airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) because I've used it before and like the ruleset. It's absolutely massive and comprehensive. However, these rules enforced style on a codebase which evolved along with it. When applied to our codebase ESLint threw a few thousand errors and warnings. So we put every file into a big `.eslintignore` and promised to lint it when we could. This didn't happen. The static friction was too damn high.

![static friction](http://ummalqura-phy.com/HYPER1/fsta.gif)

Applying a ruleset that was based on a more evolved codebase, a codebase we want in the future, is simply not feasible right now. We can't cheat the process that results in a clean codebase like yours or Airbnb's by forking their linting rules. We cannot pay the huge lump-sum of engineer time to fixing each rule right now (and right now must happen since our builds fail if linting fails). [This pr](https://github.com/jwplayer/jwplayer/pull/1841) represents the fulfillment of this issue - a compromise which helps us overcome the static friction of that initial linting push. It's a simplified set of rules that I was able to apply to the entire codebase in a few hours. It's not comprehensive but it's by no means a slouch.

Don't worry - this isn't the final list of linting rules. Our set will evolve over time and our codebase will continue to improve. We hold tech debt meetings every two weeks where we generate tickets like this one. We're starting to get more serious about it. I'm personally committed to improving this codebase, but I'm also personally committed to getting shit done for JWP. The real challenge is doing both of these things at once.

It's great that you dropped a comment and I'm glad that you did. Being an open-source project I love input from people using our code. We encourage everyone (yes, you!) to make their own tech debt issues against this repo whenever you see something that could be better. If we like it, we'll do our best to make it happen.

**Comment by jthomerson** [comment]
Thanks for the thorough reply @johnBartos. It's good to hear that you're moving in a solid direction. I guess just the description of the issue initially didn't paint the full picture, so I'm happy to see the clearer picture with your comment.

**Comment by johnBartos** [comment]
Resolved, rules are simplified and we've been adding more
