### ISSUE TITLE
Guidance for click-to-run cases.

### ISSUE THREAD

**Issue by jdalton** [jwplayer/jwplayer#1846]
With [Edge and Chrome switching to click to run](https://arstechnica.com/information-technology/2016/12/flash-will-become-click-to-run-in-edge-chrome-in-2017/) later this year I'm wondering if you all have any suggestions for how to handle it with jwplayer.

For Edge, when testing their insider release, click-to-run removes flash from the `navigator.plugins` collection so jwplayer thinks Flash isn't on the system. This leads to cases where no content is displayed. Do you all have a fallback to prompt to install Flash if needed?

><img src="https://cloud.githubusercontent.com/assets/4303/23241326/5a85b796-f927-11e6-8137-38d3f1dedaa5.png" width=90%>

**Comment by johnBartos** [comment]
@jdalton The solution is to not use flash. We fully support both hls and dash content. What's your use case that you still need to use it?

**Comment by jdalton** [comment]
> What's your use case that you still need to use it?

I'm on the Edge team looking at a bug report that [Mr. Trash Wheel Live](http://baltimorewaterfront.com/healthy-harbor/mr-trash-wheel-live-feed/) doesn't work and looking for either a code solution or guidance I can ping them on how to handle it. It's a live video feed.

**Comment by johnBartos** [comment]
@jdalton I believe the real fix here is to get them onto JW7 - we dropped official support for JW6 on 1-31-16. Any code fix we make right now wouldn't reach them since we cannot backpatch that version (and it looks like they're a self-hosted player, anyway). I'm talking to our support team to see if they've lodged a ticket already. If not, we'd like them to reach out so we can work out some sort of upgrade path.

If Mr. Trash Wheel is insistent on using flash, though, I believe you can hack a solution using the [JW6 Api](https://support.jwplayer.com/customer/en/portal/articles/2051720-jw6-javascript-api-reference). What you'd listen for is `onSetupError`, and if the message matches `FLASH NOT FOUND` or something like that you can proceed with your upgrade popup from there. I don't know the exact message coming from the event though.
