### ISSUE TITLE
Missing functionalities VR

### ISSUE THREAD

**Issue by joshuavdhof** [jwplayer/jwplayer#1885]
I’m trying to use your plugin to accomplish some functions in VR video’s but I’m having some problems.

What I want to do with the VR plug-in
•	Set the orientation of the view aria to a certain location to force a user to look at a specific location.
•	Detect when a video is in 360 degree.
•	Using VR glasses like Google Cardboard or Samsung VR

Problems that in facing regarding vr.js
•	Not able to set orientation.
•	Don’t know what values getOriantation() is giving back (0.0.0.1).
•	No source code of vr.js.
•	Not able to create new functions in vr.js because sources file is not available.

If you can help me with these problems that would be great.

**Comment by RikHeijdens** [comment]
Hey Joshua,

1) We don't currently allow developers to force a specific orientation, just wondering is there a specific use case for this? By default we position the camera so that the user starts to watch in the "middle" of the video as if you were watching it normally. We do however offer a method `resetPose` which allows you to reset the camera.
2) `getOrientation()` returns a [quaternion](https://en.wikipedia.org/wiki/Quaternion) which represents the orientation of the camera/HMD. We also have a method `getOrientationAngles()` which returns the orientation of the camera as Euler angles in a right-hand sided OpenGL coordinate system.
3) The Google Cardboard should work out of the box on Android devices. You can enter VR mode by tapping the "Cardboard" icon when using the player on a mobile phone.

Unfortunately `vr.js` is currently not open-source, but if you have any specific feature requests feel free to open a feature request here.

**Comment by joshuavdhof** [comment]
Hey @RikHeijdens,

Thank you for the quick replay.
1. We want to use a layer to place object in front of the video. And if a object pops on the screen we would like to orientate the camera to that specific object. And we want to use the getOrientation() function to get the orientation and calculate the pixel or % to place the object. So when you point the camera to that location on the screen the object will be visible.
2. Thank you for explaining the values. Is there some documentation for this plug-in that I can read.
3. The cardboard icon is not showing on my devices but we don’t show the jwplayer but our own layer in front of the jwplayer. So is it possible to trigger the cardboard view with a API call?

For a feature request, a way to set the camera to a specific location so that its able to force the user to look at a specific part in the 360 video, and a way to trigger the cardboard view without button.

**Comment by RikHeijdens** [comment]
Hmm, 1) might be a tough one. You can only really do something like that when you're actually rendering into the same WebGL context as we're rendering the video in. Then you can convert object space into camera space in order to verify whether a user is looking at an object. I don't think this will be easy to do with the current setup.

Using any other approach you'll likely experience issues when "VR Mode" (Cardboard mode) is being activated since we only render the canvas attached to 'our' WebGL rendering context in that case.

2) Unfortunately we don't offer public documentation at this time. Here is a short summary of methods:

```javascript
vr = jwplayer('container').getPlugin('vr'); 
if (vr) { 
  /* VR plugin loaded */ 
  
  // Retrieve the orientation of the Camera/HMD as a quaternion.
  orientation = vr.getOrientation();

  // Retrieve the orientation of the HMD/Camera as euler angles.
  // 
  // The returned yaw is relative to the initial yaw of the sensor
  // when it was first read or when resetPose() was last called in
  // case of devices featuring an gyroscope/accelerometer.
  // 
  // The angles are provided in radians within the following intervals:
  // - Yaw: [-π, π]
  // - Pitch: [-π/2, π/2]
  // - Roll: [-π, π]
  // 
  // In the situation of gimbal lock the calculation of Euler angles
  // becomes numerically unstable and 0 will be returned for roll.
  angles = vr.getOrientationAngles();

  // Enter VR/Cardboard Mode (on supported devices/browsers).
  vr.enableVRMode(true);

  // Exit VR mode.
  vr.enableVRMode(false);

  // Resets the pose for the camera.
  // This should be called only in sitting-experiences
  // or when VR mode is not enabled.
  vr.resetPose();

  // Register an error listener.
  vr.on('error', error => {
    console.warn('VR Error: %O', error);
  }
}
```

3) You can use `enableVRMode(bool)` to do this.
