### ISSUE TITLE
Analyze impact of temporary DOM element creation for utils

### ISSUE THREAD

**Issue by johnBartos** [jwplayer/jwplayer#2054]
In `utils/dom` and `utils/css` (and perhaps elsewhere), we create a temporary `div` and read/write its `innerHTML` as a hack to decode strings. We should analyze the performance of this operation and if necessary, use only one "dummy" div per player.

**Comment by robwalch** [comment]
What we need to do now is have a look at DOM creation in the controlbar and menu. By composing these elements from many smaller HTML components that each parse text into element instances we incur a lot of over head parsing each button and container. It would be great to have templates that generate more elements at once, or compose the HTML string another way before doing only one parse and then adding to controls.

**Comment by robwalch** [comment]
@egreaves @johnBartos @radium-v @hghazzi @karimJWP 
Avoiding html/svg parsing altogether in some cases may also help. Both innerHTML and DOMParser create document in memory to perform the parsing and block until done.

While profiling, 80ms for controls creation makes a good target for optimization. Because these svg icons were loaded as fonts, their rendering did not block the completion of setup, and they do here:
<img width="786" alt="screen shot 2017-08-22 at 10 50 46 pm" src="https://user-images.githubusercontent.com/333258/29596750-90c0e7b0-878c-11e7-95c3-05d2ffb49598.png">

Controlbar, menu and sharing require a lot of work up front. Lazy DOM creation for menu and sharing which aren't even displayed at ready would also speed things up:
<img width="671" alt="screen shot 2017-08-22 at 10 51 20 pm" src="https://user-images.githubusercontent.com/333258/29596756-95327052-878c-11e7-81c2-14976da17669.png">

Here we can see the pattern for each button in the controlbar. Batching this DOM creation and parsing into a single template could have big benefits:
<img width="616" alt="screen shot 2017-08-22 at 10 51 39 pm" src="https://user-images.githubusercontent.com/333258/29596767-9a9d30fe-878c-11e7-8918-70068e588247.png">

**Comment by robwalch** [comment]
I've already made a few passes at improving performance by grouping parsing of html. The last round was done as part of security enhancements around dealing with html input and merging related into jwplayer-commercial https://github.com/jwplayer/jwplayer-commercial/commit/3aaef55947b52c7be779b21638b18eb469d3b215
