### ISSUE TITLE
Whittle down Underscore

### ISSUE THREAD

**Issue by johnBartos** [jwplayer/jwplayer#2084]
Let's revisit our usage of Underscore and replace any methods with a browser-supported native alternatives

- Underscore custom build
- Update Underscore

**Comment by robwalch** [comment]
Let's start listing how to replace these. For example:

`_.map(array, () => {})` => `array.map(() => {})`

`_.map(object, (value, key) => {})` => `Object.keys(object).map((key) => { const value = object[key]; })`

**Comment by robwalch** [comment]
@johnBartos We could convert underscore.js to ES6 modules and then only import the ones we want or `import * as _ from 'underscore'`. I still agree with removing methods that are replaceable with native JS, just an idea that might make things easier since this type of refactor would surface all the places underscore is being used in the player projects (plugins would still need work).

**Comment by hghazzi** [comment]
We can try to use codemods to do this across our codebase

https://github.com/cpojer/js-codemod#underscore-to-lodash-native

https://github.com/cpojer/js-codemod/blob/master/transforms/underscore-to-lodash-native.js
