### ISSUE TITLE
Double Entry in Player with Multiple Audio Streams

### ISSUE THREAD

**Issue by Lachlan74** [jwplayer/jwplayer#2093]
### Expected Behavior

When more than one audio stream present, the selector should have one entry for each stream.

### Actual Behavior

The first audio stream is listed twice. 

### Steps to reproduce

1. Play a video file with two or more audio streams. E.g. 
https://media.app.viostream.com/525e1c12-2d40-4ebe-bc08-a3a20096147e/f1d42069-74dd-4fa9-a0b6-3ff4f1c52ed5/7daf22fa-baae-400b-8e39-a76200eca357.m3u8

2. Click on Audio Selector
3. Observe the first Audio stream is listed twice.

### Environment

- *PC/MAC*
- *Windows 10/ Sierra*
- *Chrome/FF | Latest*
- *7 | https://publish.viostream.com/play/7ja3dtb4zyss8*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by egreaves** [comment]
Hi @Lachlan74 - 

There are 2 English audio tracks in the stream's manifest. See below:

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="program_audio",LANGUAGE="en",NAME="english",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=917289,CODECS="avc1.4d4015,mp4a.40.2",RESOLUTION=512x238,AUDIO="program_audio"
56ec0ada-075d-40c2-a8ea-d7ef72d97bb1.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="program_audio",LANGUAGE="en",NAME="english",AUTOSELECT=YES,DEFAULT=NO,URI="b011f345-6668-4bab-acd3-a76200ec77a0.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="program_audio",LANGUAGE="de",NAME="german",AUTOSELECT=YES,DEFAULT=NO,URI="b0c3584c-7510-409f-a1c7-a76200ec77a0.m3u8"
```

One of the English tracks contains a `URI` attribute and is not the default; the other doesn't contain have a `URI` and is marked as the default track for the stream. 

Since the [HLS spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4.2.1) states that the `URI` attribute is optional for audio renditions, we include both in the menu. Note that this does not affect the user's ability to hear audio in either language. However, an easy solution is updating the manifest to contain unique audio rendition entries.
