### ISSUE TITLE
Fast click on media container leads to "Cannot read property 'load' of undefined" - error

### ISSUE THREAD

**Issue by aramin** [jwplayer/jwplayer#2112]
### Expected Behavior

The user can't click on the media container (.jw-media) until the player is not fully initialized.

### Actual Behavior

If the user has a (very) slow internet connection the media container is clickable and maybe tries to play the video, even though the controls are not visible at this point and the player hasn't finished its setup procedure. This leads to the error "Cannot read property 'load' of undefined".

### Steps to reproduce

1. Use a mobile device (Chrome Dev Tools - iPhone 6 e.g.)
2. Throttle network speed to 3G
3. Open the page with a video player
4. While Loading click on the media container continuously

### Environment

- Happens on all mobile devices (maybe also non mobile -  not tested yet)
- macOS Sierra 10.12.2
- Google Chrome Version 59.0.3071.86 
- 7.11.2
- example page: https://www.welt.de/sport/video165672968/Riesiges-Geschenk-fuer-Ronaldo.html (we will roll out a hotfix this evening, so it won't be reproducible on that page in a few hours)

<img width="536" alt="bildschirmfoto 2017-06-19 um 13 46 51" src="https://user-images.githubusercontent.com/7523087/27283900-c2a6dc12-54f6-11e7-9c1b-31408adf5fa0.png">

**Comment by johnBartos** [comment]
@aramin Thanks for the report! The Player shouldn't allow the user to enter a bad state; we'll look into this.

**Comment by squarecandy** [comment]
I'm also experiencing this issue:

An element that looks like a play button is clicked

The player and a bunch of other content is loaded in a lightbox via AJAX

The original code loaded looked like this: 

`<div class="jwplayer-container"><div id="jwplayer123">player loading...</div></div>
				<script type="text/javaScript">
				var playerInstance = jwplayer("jwplayer123");
				playerInstance.setup({
					"sources":
						[{
							"file": "https://s3.amazonaws.com/[redacted]/filename.m3u8"
						}],
					"height": "40",
					"width": "auto",
				}).setControls(true).play(true);
				</script>`

But I ended up needing to put a small delay in before .play() was called or it would fail with "Cannot read property 'load' of undefined" in some cases.

`<div class="jwplayer-container"><div id="jwplayer123">player loading...</div></div>
				<script type="text/javaScript">
				var playerInstance = jwplayer("jwplayer123");
				playerInstance.setup({
					"sources":
						[{
							"file": "https://s3.amazonaws.com/[redacted]/filename.m3u8"
						}],
					"height": "40",
					"width": "auto",
				});
				playerInstance.setControls(true);
				setTimeout(function () {
					playerInstance.play(true);
				}, 500);
				</script>`

**Comment by johnBartos** [comment]
@aramin @squarecandy Can you confirm in the latest version (7.12.3)? I just tried with your steps (throttling to 3G) and I didn't experience any errors

**Comment by squarecandy** [comment]
Using the hosted player js here: https://content.jwplatform.com/libraries/SGZVwVTN.js
I assume this is automatically updated?
But using it with our own file hosting.

I produced the error originally by doing the following:
- Load a very long page of HTML that doesn't have any players on it
- Before all of the images and other file assets of the original HTML page or loaded, click a link that loads the player code inline via ajax and applies `.play(true)`. 

Sorry I don't have an example that reproduces the error anymore since I fixed it by adding a small delay. You can check out the site here: https://bang30dev.bangonacan.org/#archive

Once all of the page images and assets from the original page completely loaded, getting the players by AJAX inline with autoplay worked fine.
