### ISSUE TITLE
m3u8 live video format not supporting

### ISSUE THREAD

**Issue by kumarweblogicx** [jwplayer/jwplayer#2122]
### Expected Behavior

m3u8 videos support

### Actual Behavior

 m3u8 videos are not playing "Error loading player: No playable sources found"

### Steps to reproduce

1. I have downloaded github master code.
2. Follow the instruction mentioned in readme file.
3. Created a livestream and test the video url to jwplayer(github source).

### Environment

- *hardware | device*
- UBUNTU  | 16.04*
- Chrome |  58.0.3029.110 (64-bit)*
- V7.12.0 | https://wowza.jwplayer.com/live/jelly.stream/playlist.m3u8

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by waxidiotic** [comment]
HLS playback requires the commercial version of the player and a paid license subscription. The open source version of the player is equivalent in feature set to the "Free" account level found on https://www.jwplayer.com/pricing.

You would need a Premium account, or higher, and use the version of the player from the dashboard in order to playback HLS content.

**Comment by johnBartos** [comment]
@waxidiotic Is correct
