### ISSUE TITLE
YouTube Support

### ISSUE THREAD

**Issue by erikdonohoo** [jwplayer/jwplayer#2233]
Our company only recently noticed your banner about no longer maintaining your YouTube plugin.  I'm not sure what the right avenue is for a request like this, but would your company consider keeping it and maintaining it if our company dedicated resources to helping keep it functional?

**Comment by esboyd** [comment]
@erikdonohoo YouTube as a provider in JW Player 7 has not been maintained due to very low usage, unannounced changes to the YouTube API that makes it difficult to stay on top of, and it does not interact well on mobile with the JW Player UI. YouTube provider has been completely removed from JW8.

You are able to create and maintain your own YouTube support through our provider sdk. Please reach out your account manager and let them know your situation and they can also work with you to move content to JW Player or another location that is reliable and will always play in JW Player.

**Comment by spello** [comment]
How can you claim that it has low usage? That's ridiculous. Don't you see that many of us expect you to maintain YT integration? We are even ready TO PAY.

**Comment by esboyd** [comment]
@spello - YouTube videos represent .01% of all plays across paid and non-paid editions of JW Player. The cost to maintain the integration is too high based on this usage.

**Comment by spello** [comment]
Do you store such data even when analytics are disabled and self-hosted player is used?

**Comment by esboyd** [comment]
@spello as this ticket is closed, please reach out to your account manger for more information regarding our YouTube support and so your request to have it is documented with your account. 

We have network wide insight into usage statistics. But again, it is not just the low usage as the motivation behind dropping support - it is not scaleable when YouTube updates their API and there are UX issues that are a great concern to us, specifically how you pass interactions through the API to our UI, which does not work on all devices.

**Comment by johnBartos** [comment]
Locked for now. Youtube is deprecated in JW8. If you want to keep using the Youtube provider, use JW7 or create a custom provider which plays Youtube videos. We have some documentation on that here (https://github.com/jwplayer/jwplayer-sdks/tree/master/providers) and are happy to help out here on Github. We have plans to open source our Youtube provider but do not have a timeline right now.
