### ISSUE TITLE
unable to initialize multiple players on elements without IDs

### ISSUE THREAD

**Issue by trinonsense** [jwplayer/jwplayer#2382]
### Expected Behavior
multiple players initialized

### Actual Behavior
only one player is initialized

### Steps to reproduce
no id code: https://codepen.io/trinonsense/pen/KXzVNZ
with id code: https://codepen.io/trinonsense/pen/JrXXOE

### Environment
- *hardware | device*: n/a
- *operating system | version*: n/a
- *browser | version*: n/a
- *JW Player version | url*: v7/8

**Comment by robwalch** [comment]
Hi @trinonsense, please provide the player version or branch you are testing in.

I highly recommend you assign an id to the elements you pass to setup. If you don't the player should do that for you, but this isn't a use-case we test for.

**Comment by robwalch** [comment]
@trinonsense have a look at https://github.com/jwplayer/jwplayer/compare/feature/support-elements-with-no-id?expand=1

This would assign a data attribute "data-jwplayer-id" to elements queried with `jwplayer(domElememt)` which do not have an id. The attribute is removed when `jwplayer().remove()` is called, and it is not present on the player element after setup, because the player always assigns an id to elements it creates.
