### ISSUE TITLE
DVR-live: timer

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#2399]
### Expected Behavior
In 'dvr-live' mode, the timer should not display.

### Actual Behavior
Timer shows "-0:27", "-0:26", "-0:25" and disappears.
video attached
![jw8-dvr-live-gif](https://user-images.githubusercontent.com/9075761/30704838-32e2b298-9ef4-11e7-9a1c-a8d0f255e957.gif)

### Environment

- *operating system | macOS 10.12.6
- *browser | chrome 60.0.3112.90
- *JW Player version | 8.0-beta-2

**Comment by robwalch** [comment]
This happens when the stream falls behind the 25 second live edge. which can happen for streams with large or uneven segments. @johnBartos @karimJWP did we make any improvements to this behavior in beta.3? I would expect the live icon to toggle state when the stream falls behind "live" and for the UI threshold to be greater than the seek threshold of 25 seconds.

**Comment by karimJWP** [comment]
@robwalch correct, the live icon should toggle state, but we fail to do so when a stream falls behind because we do not check the state on time progress; for efficiency, we limit the check to on seek and state changes. I'll open a ticket for this, we might be able to hide the time when the live icon is solid

**Comment by robwalch** [comment]
@mtoczko how's this looking for you in v8.0.0-rc.3?

**Comment by mtoczko** [comment]
@robwalch No change.

**Comment by mtoczko** [comment]
Refresh and link to video [DVR]
`http://b028.wpc.azureedge.net/80B028/SampleStream/595d6b9a-d98e-4381-86a3-cb93664479c2/b722b983-af65-4bb3-950a-18dded2b7c9b.ism/Manifest(format=m3u8-aapl)
`
