### ISSUE TITLE
API: Safari play(true) blocked

### ISSUE THREAD

**Issue by seesoe** [jwplayer/jwplayer#2421]
### Expected Behavior

On Safari when calling `jwplayer().play(true)`, the player should play the video

### Actual Behavior

Safari blocks the event with the following console message
```
NotAllowedError (DOM Exception 35): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
play
Z — provider.html5.js:1:15476
play — provider.html5.js:1:20436
playVideo — jwplayer.js:2:8318
(anonymous function) — jwplayer.js:2:2573
s — jwplayer.js:1:10771
trigger — jwplayer.js:1:9939
set — jwplayer.js:4:22824
loadVideo — jwplayer.js:2:8121
(anonymous function) — jwplayer.js:3:23037
e — jwplayer.js:4:23530
N — jwplayer.js:3:23013
(anonymous function) — jwplayer.js:3:20015
play — jwplayer.js:3:10150
(anonymous function) — player.html:80
```

### Steps to reproduce

```html
<div id="player"></div>

<script type="text/javascript" src="/includes/js/jwplayer/jwplayer.js"></script>
<script type="text/javascript">jwplayer.key = "my_key";</script>

<script type="text/javascript">
    jwplayer('player').setup({
        file: '//content.jwplatform.com/videos/C4lp6Dtd-640.mp4'
    });

    setTimeout(function () {
        jwplayer().play();
    }, 500);
</script>
```

### Environment

- MacOS 10.12.6
- Safari Version 11.0
- Tested with jwplayer 7.10.4, 7.12.8, 8.0b3, 8.0 does not return the warning in safari but it still doesn't not play.

**Comment by robwalch** [comment]
@seesoe This is expected in browsers with an autoplay policy. `jwplayer().play()` and `videoElement.load()` must be called in the context of a user gesture meaning a click or tap event.

In JW8 we've removed the toggle argument from `play(true)` so you can just call `play()`. If you want to toggle playback use `playToggle()`.

Since beta.3 you can chain setup and play `jwplayer().setup().play() but we recommend you use autostart rather than call play on timeout.

We're still looking at Safari 11. We expect that if it's set to now allow playback without a click, that the `play()` will load the video and put the player in a paused state. You can listen for a "playAttemptFailed" event to detect that the play was not allowed.

**Comment by aorfanos1** [comment]
Would you like me to send an email about it to BCH?

**Comment by robwalch** [comment]
Closing this issue. If you cannot start playback when calling `jwplayer().play()` inside a click or tap event handler, please open a new issue.
