### ISSUE TITLE
JWPlayer 8 Release broke players using version 7

### ISSUE THREAD

**Issue by sw360cab** [jwplayer/jwplayer#2513]
After release of Jwplayer 8 old players (jwplayer 7 based) result broken.

In my case using 
http://jwpsrv.com/library/XpMfzFwiEeOfZhIxOQfUww.js

results in 

Error loading player:
No playable sources found

with a jwplayer(...).onSeek(...).onPause is not a function

**Comment by dannyfinks** [comment]
@sw360cab in JW Player 8 we deprecated those API calls in favor of using the on('seek') and on('pause') convention. However, we've created a backwards compatibility script for your use case. 

You can find our release notes that mention these changes here:
https://support.jwplayer.com/customer/portal/articles/2870361

If you are self hosting you should have the backwards compatibility script available in your zip otherwise you can use http://ssl.p.jwpcdn.com/player/v/8.0.0/jwplayer.compatibility.js below the jwplayer script.

**Comment by dannyfinks** [comment]
Closing this out. Feel free to reopen or reach out again if you continue to face any challenges.
