### ISSUE TITLE
Youtube player throws JS error "Y.getVideoData is not a function'

### ISSUE THREAD

**Issue by bjmrey** [jwplayer/jwplayer#2525]
A new error started popping up today and it's quite critical for us. We're using JW Player v. 7.7.4 to play Youtube videos. **Edit: we upgraded to v.7.12.11, same issue**. When clicking on play, an exclamation mark appears and the error below is thrown. When clicking again it does play.

```
TypeError: Y.getVideoData is not a function
at V (/player/v/7.7.4/provider.youtube.js:1:2920)
at load (/player/v/7.7.4/provider.youtube.js:1:3702)
at l.a (/player/v/7.7.4/provider.youtube.js:1:2877)
at l.<anonymous> (/player/v/7.7.4/provider.youtube.js:1:1218)
at b (/player/v/7.7.4/provider.youtube.js:1:1698)
...
```
See behavior on our website [here](https://fr.ilini.com/post/lanvin-in-crisis).
A similar issue was reported by someone else [here](https://support.jwplayer.com/customer/portal/questions/17189166--jwplayer-problem-with-youtube). 

I know that JW Player has dropped Youtube support because of the Youtube API's inconsistencies but would love to get some help. For our use case JWPlayer 7 + Youtube is still our best choice and we'd like to keep using it.

**Comment by jalamprea** [comment]
I have the same issue since yesterday :(

**Comment by robwalch** [comment]
Related issues on stackoverflow:

- https://stackoverflow.com/questions/47282235/jwplayer-v7-xx-getvideodata-is-not-a-function-issue
- https://stackoverflow.com/questions/47282202/youtube-iframe-api-getvideodata-is-removed-how-to-get-title

**Comment by jamesherrieven** [comment]
While you wait for work from Google, I've created a plugin to fix it in the meantime. Download it from here:

https://www.dev.powered-by-haiku.co.uk/solutions/getvideodata/code/getvideodata.js

Apply it as you would any other JW plugin:

```
"plugins":{
 "getvideodata.js":{}
 }
```

**Comment by bjmrey** [comment]
Awesome James!

**Comment by jalamprea** [comment]
You rocks James!!!
Thanks to you we have our music videos with collaborative playlist service up again :)
https://play.festa.co/

**Comment by binjuhor** [comment]
It working for me thanks James!!!!

**Comment by hoyce** [comment]
Great job!

**Comment by braindeaf** [comment]
I've tried the solution. It appears that the plugin is load just after the YouTube video plays. Any ideas?

**Comment by jamesherrieven** [comment]
@braindeaf - Are you using "autostart: true"? If so, are you using the updated plugin script (v1.1)? Do you have a page I can look at to try an figure out the issue?

**Comment by braindeaf** [comment]
Hi @jamesherrieven thanks for getting in touch yes indeed we're using autostart. Another trigger on the page loads JWPlayer instead of autoloading everything and therefore autostart is appropriate.

http://www.pledgemusic.com/projects/gratefuldub/updates/87609

I can only see the 1.0 version up here. Is it cached and therefore I can't see 1.1?

**Comment by braindeaf** [comment]
Sorry, looks like we are using 1.1. I was looking at the comments and reading 1.0.

**Comment by eye8** [comment]
We had JWPlayer v7.10.6 before and encountered the same problem. We upgraded to v7.12.10 which fixed Chrome but other browsers such as Safari and FF still don't work.

For now, I'm using CSS to hide JWPlayer's big play button so that user can directly interact with the YouTube iframe player. This way YouTube video will play. 

```
.jwplayer .jw-display-controls {
    display: none;
    visibility: hidden;
}
```

P.S. we also add a special class to the JWPlayer instance for YouTube provider only, and hide the big play button only for YouTube video. Then when video playback is completed we remove the special class to show the replay button.

**Comment by jamesherrieven** [comment]
@braindeaf Yep, I see that you are using the correct version... Looking at the network tab, it appears that the initiator for the "getvideodata.js" library is not "jwplayer.js". I wonder whether the pre-loading technique you are using is causing a problem.
Can you remove the reference to "getvideodata.js" from here just to see if that's the problem: 
`$.cachedScript("/pipeline/vendor/jwplayer.js","/pipeline/vendor/jwplayer/getvideodata.js")`

**Comment by braindeaf** [comment]
HI @jamesherrieven, you were right I was trying to load the plugin early just in case it was a speed of the network thing. And I've removed that and still the console shows the following.

Uncaught TypeError: t.getVideoData is not a function
    at C (jwplayer.html5.js:26)
    at e.html5.youtube.r.load (jwplayer.html5.js:28)
    at e.html5.youtube.Y (jwplayer.html5.js:26)
    at w (jwplayer.html5.js:24)
    at K.f.I (www-widgetapi.js:66)
    at W.f.l (www-widgetapi.js:114)
    at W.f.J (www-widgetapi.js:127)
    at S.g (www-widgetapi.js:143)
    at g (www-widgetapi.js:95)
C @ jwplayer.html5.js:26
r.load @ jwplayer.html5.js:28
Y @ jwplayer.html5.js:26
w @ jwplayer.html5.js:24
f.I @ www-widgetapi.js:66
f.l @ www-widgetapi.js:114
f.J @ www-widgetapi.js:127
S.g @ www-widgetapi.js:143
g @ www-widgetapi.js:95
postMessage (async)
mh.sendMessage @ www-embed-player.js:447
l.oa @ www-embed-player.js:457
l.sendMessage @ www-embed-player.js:458
l.va @ www-embed-player.js:454
mh.A @ www-embed-player.js:446
postMessage (async)
f.C @ www-widgetapi.js:121
f.H @ www-widgetapi.js:118
setInterval (async)
wb @ www-widgetapi.js:97
(anonymous) @ www-widgetapi.js:119
g @ www-widgetapi.js:95
(anonymous) @ VM16407:2
k @ VM16407:2
V.o @ VM16407:2
t @ VM16407:2
F @ VM16407:2
z @ VM16407:2
p @ VM16407:2
V @ VM16407:2
a.nKh @ VM16407:2
bg @ VM16407:2
qe @ www-embed-player.js:275
(anonymous) @ www-embed-player.js:274
f @ www-embed-player.js:258
(anonymous) @ www-embed-player.js:249
setTimeout (async)
U @ www-embed-player.js:255
(anonymous) @ www-embed-player.js:259
l.G @ www-embed-player.js:187
ce @ www-embed-player.js:262
(anonymous) @ www-embed-player.js:267
setTimeout (async)
d.onload @ www-embed-player.js:268
getvideodata.js:10 Powered By Haiku: "getVideoData" fix applied...

I've had to revert the plugin in production anyway because the standard mp4 videos loaded in the same way stopped playing after the plugin was load. Something I've seen in development too. Dang.

**Comment by jamesherrieven** [comment]
@braindeaf So after quite a bit of investigation, it appears that by including an explicit **"skin"** setting in your JW6 setup, coupled with **"autostart":true**, and the autostarting file being a YouTube file, any attempt to cancel an autoplay is ignored - hence you are getting the _t.getVideoData is not a function_ error before the _Powered By Haiku: "getVideoData" fix applied..._ message, as JW Player is continuing to try and play the file.

One solution would be to remove the "skin" parameter. Another would be to change the approach to not autostart and just render the player when the page loads (which might help in the longer term with the way browsers are going). 

Either way you shouldn't include the 'getvideodata.js' file in the caching function: `$.cachedScript("/pipeline/vendor/jwplayer.js","/pipeline/vendor/jwplayer/getvideodata.js") `

You might also consider updating to the final version of JW6.

**Comment by braindeaf** [comment]
Thank you so much for looking into this for us @jamesherrieven it's about time we looked at upgrading. In fact the most recent hosted player appears to work fine for mp4 and YouTube. Again thank you.

**Comment by gusper** [comment]
I just noticed that getVideoData() is working again. This may be an occasion where laziness paid off for me. Anyone know if YouTube intends to keep supporting it or not?

**Comment by robwalch** [comment]
Closing. It appears Youtube fixed the issue.
