### ISSUE TITLE
Duplicate entries with DASH multi audio in quality settings

### ISSUE THREAD

**Issue by Orygin** [jwplayer/jwplayer#2791]
### Expected Behavior

JWPlayer should only display video qualities available. This works fine for m3u8 streams using HLS.
![screen shot 2018-03-19 at 10 32 15](https://user-images.githubusercontent.com/188375/37587879-d705603e-2b60-11e8-826b-5245144d7480.png)

### Actual Behavior

Duplicate quality entries for each available sound quality and video quality. Stream is using DASH with ABR.
![screen shot 2018-03-19 at 10 31 44](https://user-images.githubusercontent.com/188375/37587898-e69579c6-2b60-11e8-99f4-ab0d2bcd3265.png)

### Steps to reproduce

1. Test stream with DASH ABR with JWPlayes 7 & 8
2. Notice duplicate entries inside the quality selection

### Environment

- MacOS, Linux, Windows
- Firefox, Chrome
- 7.12.11, also happen in JWPlayer test page with JWPlayer 7 & 8
-  Test stream URL : DASH: https://vodl.l3.freecaster.net/vod/freecaster/geo/open/QYYUCa5BxK/master.mpd
 HLS (expected behavior) : https://vodl.l3.freecaster.net/vod/freecaster/geo/open/QYYUCa5BxK/master.m3u8
Tested using JWPlayer's test player : https://developer.jwplayer.com/tools/stream-tester/

**Comment by messenjer** [comment]
Additional info from Unified Streaming support

> This is JWPlayer behaviour.
> It doesn't seem to understand or fully support ABR audio tracks.

In the reference player it's shown differently and in a more appropriate (correct) way:
 
* https://reference.dashif.org/dash.js/v2.6.6/samples/dash-if-reference-player/index.html?url=https://rtbf-vod.l3.freecaster.net/vod/rtbf/geo/open/X/XAq8xln9ms/master.mpd

![firefox_screenshot_2018-03-20t10-07-51 224z](https://user-images.githubusercontent.com/80677/37648557-938abeba-2c2f-11e8-9d37-70c34c42dca1.png)

**Comment by johnBartos** [comment]
@messenjer @Orygin This is expected behavior. JW first sorts qualities by the height label (720p, for example) but when it notices duplicate labels, it then sorts each "duplicate" group by bandwidth. When this happens the viewer will see the bandwidth in parentheses next to the width.

The [Shaka Player demo](https://shaka-player-demo.appspot.com/demo/#asset=https://vodl.l3.freecaster.net/vod/freecaster/geo/open/QYYUCa5BxK/master.mpd;lang=en-US;build=uncompiled) which we use internally to play DASH content also reports the same renditions we do:

![screen shot 2018-03-20 at 11 00 26 am](https://user-images.githubusercontent.com/5042276/37662678-f6d459a6-2c2d-11e8-88ed-daaa5b15cf57.png)


Also, I believe we do support ABR audio tracks since Shaka does too.

**Comment by Orygin** [comment]
@johnBartos Ok then what can be done to have a more user-friendly interface ?
Like have the quality settings menu splitted with Video/Audio separated, or have control to restrict which entries will be shown in the menu.

Ideally we'd have only video quality entries and the audio quality set to automatic.

**Comment by johnBartos** [comment]
@Orygin Hm I think I misunderstood, these aren't all video tracks? Let me take another look

**Comment by Orygin** [comment]
There are four video tracks with three audio tracks each. We wish to only display video tracks in the quality setting menu.
So either displaying video and audio tracks as different entries like @messenjer screenshot, or only display video tracks and have the audio track automatically chosen.

**Comment by johnBartos** [comment]
@Orygin Ok, I think I see now:


```
<Representation
        id="audio=96869"
        bandwidth="96869">
      </Representation>
      <Representation
        id="audio=128680"
        bandwidth="128680">
      </Representation>
      <Representation
        id="audio=192300"
        bandwidth="192300">
      </Representation>
```

Either Shaka is mixing these into the same object or we're interpreting the information it's giving us incorrectly. But regardless of data interpretation, our UI doesn't have a the multiple non-alternate audio tracks, so our implementation would not look like the ref player. I think our ideal solution would be to hide the alternate bitrate audio renditions and let Shaka select them via ABR, so that your quality selector would just show the video renditions.

**Comment by Orygin** [comment]
@johnBartos Yeah. I beleive hiding the alternate audio bitrate is the best solution in our case.
I guess since the dash reference player displays the information correctly that the problem comes from jwplayer.

**Comment by Orygin** [comment]
@johnBartos Hello, any update concerning this issue ?

**Comment by quebello** [comment]
Hello, any update concerning this issue ?

**Comment by karimMourra** [comment]
hi @quebello this issue was closed half a year ago. Are you still seeing these issues ? If so what version of the player are you using

**Comment by quebello** [comment]
Hello the version 8 latest
