### ISSUE TITLE
Chromecast doesn't play our HLS stream

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/jwplayer#2815]
### Expected Behavior

Casting an HLS stream to a Chromecast device should be supported.

### Actual Behavior

With our HLS streams, the Chromecast receiver triggers an error. Unfortunately, this error doesn't contain much information about the real problem.

**MacOS - Chrome 65**

It doesn't connect to the Chromecast device. It's not showing any error (with debug mode on).

**Android - Chrome 65**

It does play the first item of the playlist (MP4) but crashes when playing the second item (HLS). It logs "session_error" in the console.

### Steps to reproduce

1. Go to https://newfaithnetwork.nl/video/1-0-vraag-pasen-1
2. Click the cast button

### Environment

- macOS High Sierra and Android 7.0
- Chrome 65
- v8.2.0

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
@ChristiaanScheermeijer I'm not sure how to watch video on your site. Can you provide a player config or isolated test page that demonstrates the bug?

**Comment by ChristiaanScheermeijer** [comment]
Hi @robwalch,

Ah, I think the videos are geo-restricted on that site. Anyway, I can also reproduce this in Showcase: 

https://eduactief.jwpapp.com/m/FR8mldzU/the-student?list=KHIkuaxV
Chromecast 1st gen (1.29.104827)
JW Player v8.2.2

**Comment by hghazzi** [comment]
@ChristiaanScheermeijer I was able to reproduce it on the first url you provided, but the showcase app worked fine for me. 

It appears that the HLS streams used on NFN are not supported by the chromecast's default player, which is managed by Google. This could be due to how they are packaged. If you could provide us with an hls test stream, we can open an issue with the chromecast team.

**Comment by ChristiaanScheermeijer** [comment]
Hi @hghazzi,

Thanks for info, I have extracted the HLS stream so it can be played without URL token.

https://demo.videodock.com/video/hls/trailer-wat-zegt-de-bijbel/Manifest.m3u8

FYI on the original stream I get the following errors using mediastreamvalidator. These errors are not visible in the URL from above.

```
--------------------------------------------------------------------------------
MUST fix issues
--------------------------------------------------------------------------------

Error: Illegal MIME type
--> Detail:  MIME type: application/octet-stream
--> Source:  https://dc-nfn-cdn-media.newfaithnetwork.nl/1-0-trailer_wzdb-1/video/hls/Manifest.m3u8

--> Detail:  MIME type: application/octet-stream
--> Source:  video-H264-1080-3000k.m3u8

--> Detail:  MIME type: application/octet-stream
--> Source:  Audio-en.m3u8
```

**Comment by hghazzi** [comment]
That might actually be the issue, we need the correct mime type when passing the stream to the chromecast device. Are you able to fix the mime type and test it?

**Comment by DutchChannels** [comment]
Hi, 

I moved one of the HLS streams to a test server, where it is served with the right mime types. The mediastreamvalidator does not return the mime type errors now, but both Chromecast and Airplay still doesn't work.

Page with test player: https://test.newfaithnetwork.com/test.html
Stream being used: https://test.newfaithnetwork.com/1-0-hobr-2015-1/video/hls/Manifest.m3u8

**Comment by ChristiaanScheermeijer** [comment]
I'm getting the same `{code: "session_error", description: "LOAD_FAILED"}` error on that page. It tries to play, but stops before the first frame and resumes playback in the browser.

**Comment by ChristiaanScheermeijer** [comment]
Hi @hghazzi, do you have any updates?

**Comment by ChristiaanScheermeijer** [comment]
Short update; I've built and deployed the latest version of the jwplayer-cast-recevier application and it seems to work fine there.

**Comment by ChristiaanScheermeijer** [comment]
Updated jwplayer to 8.2.3 in the custom receiver. I see this issue now:

![image](https://user-images.githubusercontent.com/3996119/38860461-86a93caa-4230-11e8-9e9c-7e242848cb77.png)

**Comment by alenzamanyan** [comment]
@ChristiaanScheermeijer 

Were you able to solve this issue? I'm seeing a similar error when trying to cast from a self-hosted JW Player video.

Here are some details about my setup:

1) The video is in HLS streaming format. So the file that I'm passing to the JW Player Javascript API has .m3u8 extension.
2) The video is hosted on S3.
3) The video is served through CloudFront.

I tried JW Player version 7.12.13 and 8.6.3 and I am unable to cast with either.

Thanks!

**Comment by ChristiaanScheermeijer** [comment]
Hi @alenzamanyan,

Unfortunately not, we had to change the source to MPEG-Dash in Chrome browsers to make it work. 

I still believe it had something to do with the HLS and/or wrong mime type headers. Are you able to share an example HLS stream?

**Comment by alenzamanyan** [comment]
@ChristiaanScheermeijer 

Here's a stream:
http://jwplayer-chromecast.herokuapp.com/m3u8

Note that the above stream uses version 8 of the JWPlayer library, but I've also tried with version 7 and still no luck. There some details in my post on stackoverflow:
https://stackoverflow.com/questions/53800705/casting-from-jw-player-fails-for-s3-hosted-hls-video-m3u8-format

One interesting thing I noticed is that casting works if I change the CORS allowed origin configured in S3 to allow all origins:

<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <ExposeHeader>ETag</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>

However, if I specify the particular protocol and domain for the page with the stream, I observe the problematic behavior:

<CORSRule>
    <AllowedOrigin>http://jwplayer-chromecast.herokuapp.com</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <ExposeHeader>ETag</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>

I also tried adding http://*.jwpcdn.com and https://*.jwpcdn.com as allowed origins, since I believe that's where JWPlayer's Chromecast receiver is hosted.
https://support.jwplayer.com/articles/cross-domain-file-loading-reference

Allowing all origins is obviously not ideal for privacy reasons, so I'm still looking for a better solution. But it's pretty conclusive that the problem is with CORS configuration for HLS videos. I suspect that the reason is that the HLS format is made up of many files (top-level m3u8, optional resolution-specific m3u8, and ts files), so the player has to go back and forth to the server multiple times. Somehow, this causes a problem with CORS unless all origins are allowed. This is pure speculation, though. Let me know if you have any thoughts.

I'm also going to look into using MPEG-DASH instead of HLS. Thanks for the tip!

**Comment by alenzamanyan** [comment]
It turns out you also need to allow access from https://<span></span>*.gstatic.com. This is in addition to http://<span></span>*.jwpcdn.com and the domain on which the video player page is being hosted.

After these changes, here's what the CORS configuration looks like for my S3 bucket:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>http://my-domain-with-video-player.com</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
<CORSRule>
    <AllowedOrigin>http://*.jwpcdn.com</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
<CORSRule>
    <AllowedOrigin>https://*.gstatic.com</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```
