### ISSUE TITLE
8.2.x fails to load, Module not found 'setimmediate' 

### ISSUE THREAD

**Issue by dust3d** [jwplayer/jwplayer#2826]
### Expected Behavior

JW Player loads properly without errors

### Actual Behavior

Getting an error:
`   ERROR in ./node_modules/timers-browserify/main.js
    Module not found: Error: Can't resolve 'setimmediate' in '/path/to/my/app/node_modules/timers-browserify'
     @ ./node_modules/timers-browserify/main.js 51:0-23`
### Steps to reproduce
upgrade from 8.1.12 to 8.2.x

My app is failing to load after upgrading to 8.2.x (I've tried 8.2.0 and 8.2.2) 

It works on 8.1.12

The error is:
 
    ERROR in ./node_modules/timers-browserify/main.js
    Module not found: Error: Can't resolve 'setimmediate' in '/path/to/my/app/node_modules/timers-browserify'
     @ ./node_modules/timers-browserify/main.js 51:0-23

That line of code in timers-browserify/main.js is:
`require('setimmediate');`

I can see that jwplayer.js in version 8.1.12 had only one mention of setImmediate: `v=window.setImmediate;` in the `jwplayer.js` file

now, jwplayer.js in version 8.2.x uses setImmediate differently.  I can see that jwplayer.js has changed the use of `setImmediate`.
`o._immediateFn="function"==typeof setImmediate&&function(e){setImmediate(e)}||function(e){d(e,0)}`

### Environment
Using webpack, yarn

**Comment by robwalch** [comment]
@dust3d Can you provide an example using 8.2.2? timers-browserify is no longer included in the player (`webpack.config.node = false`). The check you refer to looks for `setImmediate`, and only uses it if defined. The bug in 8.2.0 was that it was defined by a polyfill added by our build process. That has been removed so that it doesn't interfere with site polyfills.

The error you pointed out is in your node_modules, not jwplayer.

The version of Webpack is not related to this issue. The issue was that Webpack was polyfilling setImmediate in v8.2.0. That was fixed in v8.2.2 (@HeidiW see https://jwplayer.atlassian.net/browse/SERV-2488 and the PR below)

https://github.com/jwplayer/jwplayer/pull/2800
https://github.com/jwplayer/jwplayer/blame/v8.2.2/webpack.config.js#L97
