### ISSUE TITLE
SubTitles are not rendered properly

### ISSUE THREAD

**Issue by srirama179** [jwplayer/jwplayer#2838]
### Expected Behavior

Subtitles should be displayed after 14s

### Actual Behavior

There are no subtitles after 14s.

### Steps to reproduce

1.  Load https://siriustranslate.com/jw3.html in Google Chrome or Firefox browser
2. Play the video and enable captions (english or any other available language) using CC menu option
3. Observe after 14s, there are no subtitles

### Environment
Google Chrome: 67
Firefox Quantom: 59

### More Details
The given URL is using jwplayer for playing a m3u8 format file which has manifest file with many webvtt files for subtitles. These subtitles have timestamps starting from 14s, so these should start displaying from 14s of video play. But they are not displayed in Google Chrome or Firefox or event Edge browser. On further analysis from chromium engine, it is found that the timestamp of these subtitles are set from javascript and these timestamps are all negative because of which these subtitles were not displayed in any of the browsers.

----------------------------------------------------------------------------------------

**Comment by robwalch** [comment]
This might have something to do with mapping cues to stream time. However, I opened your stream in Safari and do not see captions rendered there. If your stream does not work properly in Safari, it is likely an issue with your stream or captions and not something we would support.

@srirama179 Is the #EXT-X-PLAYLIST-TYPE:EVENT in your subtitles manifest intentional? That causes the manifest to be reloaded every 10 seconds. I'm not sure that hls.js supports live subtitle manifests over VOD video.

The #EXTINF:10 tag over each webvtt file does not match the range of time covered by the cues in the file. For example seq_1.webvtt has two cues with the last one ending at 24.057 so I would expect the first #EXTINF tag to have a value of at least 24.057, but no more than the start time of the first cue in seq_2.webvtt

It looks related to https://github.com/jwplayer/hls.js/pull/143. We've been holding back on merging this until we had more test streams, but again I think if captions are not showing up in Safari it's like an issue with your m3u8 or webvtt files (maybe the issues I pointed out above). cc @johnBartos

**Comment by srirama179** [comment]
@robwalch thanks for the quick look into the issue. This issue has been reported by one of the chrome users. I will forward your findings to the issue reporter. Just want to make sure that there is no issue from JWPlayer framework, so I have posted the issue here.
