### ISSUE TITLE
Audio HLS: poster image is not displayed / Android

### ISSUE THREAD

**Issue by dcharity** [jwplayer/jwplayer#2916]
Poster image should be displayed

I am using the code below to display a poster image during HLS audio stream playback m3u. It shows the preview image properly, but removes it after I press play. I would like to keep the image there while playing an audio stream.

Thanks!

`final String cimage = i.getStringExtra("cimage");

        PlaylistItem audio = new PlaylistItem.Builder().title(title).image(cimage).build();
        MediaSource mediaSource = new MediaSource();
        mediaSource.setDefault(false);
        mediaSource.setFile(url.toString());
        mediaSource.setType(MediaType.HLS);

        mediaSource.setLabel(title);
        List<MediaSource> mediaSourceList = new ArrayList<>();
        mediaSourceList.add(mediaSource);

        audio.setSources(mediaSourceList);

        playerView = (JWPlayerView) findViewById(R.id.playerView);
        playerView.load(audio);
        //playerView.setSkin(SKIN_URL);
        playerView.addOnPlayListener(new VideoPlayerEvents.OnPlayListener() {
            @Override
            public void onPlay(PlayerState playerState) {
                if (playerState.equals(PlayerState.PLAYING)) {
                    final Handler mHandler = new Handler();
                    new Thread(new Runnable() {
                        @Override
                        public void run() {
                            drawable = LoadImageFromWebOperations(cimage);
                            mHandler.post(new Runnable() {
                                @Override
                                public void run() {
                                    playerView.setBackground(drawable);
                                }
                            });
                        }
                    }).start();
                }
            }
        });`

Actual Behavior

The screen goes black and plays the audio properly.

 Steps to reproduce

Run code above using JWPlayerView object

Environment

- Pixel C
- Android 8.0
- Native Android code
- Latest JWPlayer version

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Hi @dcharity,

That looks like an issue related to using the Android SDK. Please see https://support.jwplayer.com/articles/android-and-ios-sdk-reference and submit a support case for questions related to device SDKs.

This repo is the core JavaScript player. I can tell you that the behavior you are describing happens when the player does not recognize the media as audio-only and thus treats it as a video - hiding the poster image. You'll need to contact support so that they can get a bug logged with the SDK developers and see if it's possible to set `mediaType: "audio"` in your HLS source, or get the SDK to set the proper mediaType once the HLS stream has loaded and the player can confirm which types of media tracks or codecs are present (video, audio, etc...).
