### ISSUE TITLE
How could I cover the player with a div

### ISSUE THREAD

**Issue by zhangwanqin357** [jwplayer/jwplayer#3035]
It seems that the player is always at the top-level, but I need to cover it with a div,is there any solution?

**Comment by robwalch** [comment]
Hi @zhangwanqin357,

This sounds like something you can do with CSS:

http://desource.uvu.edu/dgm/2740/in/steinja/lessons/10/l10_04.html?m=1

We intentionally avoid adding a z-index to the player container so that you can do that yourself, so I'm not sure what you mean by the player always being at the top-level.
