### ISSUE TITLE
Don't leave big white area on screen when something goes wrong

### ISSUE THREAD

**Issue by jidanni** [jwplayer/jwplayer#3120]
Note: I am just a member of the public.

I visited [this page](https://srgoideas.com/%E6%B2%99%E7%99%BC%E5%AE%A2%E7%8E%A9%E4%B8%96%E7%95%8C-2015-05-06-%E6%8E%A1%E6%9E%9C%E8%B3%9E%E8%9E%A2%E7%8E%A9%E6%9D%B1%E5%8B%A2/) and noticed a big white area in the middle of the screen.

Using Developer tools, I find it was related to "jwplayer".

I looked up "jwplayer" on Google and found this GitHub.

My only advice is, no matter what problem, be sure to fill something
(e.g., an explanation) in the big white area.

There is a black bar saying "Loading the player".

P.S., I don't own the site.

P.S., I don't own a jwplayer copy.

**Comment by jidanni** [comment]
![1](https://user-images.githubusercontent.com/1230959/46745444-a272b580-ccdf-11e8-9e38-fb33f3f94bba.jpg)

**Comment by robwalch** [comment]
Thank you for the feedback.

This is likely code on the page hiding the player error screen, or an ad that isn’t rendering any content. The player background is transparent so that site developers can use the background of their choosing. If the player’s content is being hidden by the page or there is some misuse of z-index ordering, that is up to the site to fix. Please share this feedback with the site.
