### ISSUE TITLE
On a seek/seeked event how do we know if the mouse or the keyboard triggered the event. Also how can we detect the mouse was released?

### ISSUE THREAD

**Issue by mwleinad** [jwplayer/jwplayer#3339]
We want to send a server request on 'seek' but we found out the seek event just triggers way to much when you scrub the time slider.

Is there any way to detect whether the mouse was released after a seek, or a way to prevent the seek happening that much?

**Comment by robwalch** [comment]
Hi @mwleinad,

The "seek" and "seeked" events do not provide information on why the player is seeking or whether or not the user is scrubbing the timeline.

You can check the player's internal scrubbing state via `jwplayer().getConfig().scrubbing` to check whether or not the user is scrubbing before your server request. Because this is undocumented internal state it may change in the future.

We'll have to consider providing `reason` ('interaction' or 'api'), `scrubbing` and potentially some other properties to the "seek" and "seeked" events so that you could use the events and not `getConfig()`.

In the case that the user was scrubbing when would you need to do your server request - on the first "seek" event, or the last "seeked" event?

**Comment by mwleinad** [comment]
@robwalch from a user perspective is better to do it on the last. (Basically when the user releases the mouse click)
