### ISSUE TITLE
Player customization

### ISSUE THREAD

**Issue by adamszeptycki** [jwplayer/jwplayer#3381]
I'm trying to customize the player on iOS (sorry for asking here again but questions in iOS repo are not getting responses at all)
Is there a way to change the layout of controllers (buttons)? I see only an option to change color.
I took a look at how you are drawing the UI hoping I can somehow hijack it but sadly everything is happening in UIWebView.
How can I approach customizing UI on mobile?

**Comment by karimMourra** [comment]
Hi @adamszeptycki please reopen this question in the [iOS repo](https://github.com/jwplayer/jwplayer-sdk-ios-demo/issues), and I'll address it ASAP. I'm sorry for the inconvenience; the reason I want to enforce this is because the answer will most likely be valuable to other iOS developers, and will be easier for them to find.
Thanks!
