### ISSUE TITLE
HLS abort then retry long request

### ISSUE THREAD

**Issue by lesotadil** [jwplayer/jwplayer#3400]
![image](https://user-images.githubusercontent.com/48087082/57384869-84205a00-71db-11e9-8a31-13c8cff79810.png)

I don't know it is network problem on server side or client side.
Sometime it take like 10 times (30s to 2min) than normal (less than 5s, segment length always less than 9MB) to complete a request but the next request is as fast as normal.
I know there is 20s timeout but it not work with downloading state, i also know it related on provider.hlsjs.js file but i just don't know where to begin since i'm really really bad at js, i'm using JWPlayer latest version (8.8.5)

**Comment by robwalch** [comment]
HI @lesotadil,

We would need more details to tell if the issue is related to your stream (server side(, or [hls.js](https://github.com/video-dev/hls.js/issues) (client side). Please provide a bug report with a description, steps to reproduce, actual vs expected behavior, and additional content and environement details:

- Stream URL
- Stream provider/encoder/CDN
- Browser and OS version
- Network conditions (provider, up/down speed)
