### ISSUE TITLE
[QUESTION] registerPlugin API

### ISSUE THREAD

**Issue by kvonspiczak** [jwplayer/jwplayer#3444]
Hey guys, I'm currently evaluating JWPlayer to find out whether or not I can use it to display some HTML content inside the video based on certain positions in the timeline of the video. I found a couple of code snippets online, mentioning `jwplayer().registerPlugin()` but I cannot find anything in the v8 docs. Is this undocumented/deprecated? 
Is ist still possible to build plugins for jwplayer? Maybe I dont even need a plugin for what I want to build. Any input appreciated.

**Comment by jnatalzia** [comment]
Hi @kvonspiczak, the functionality is not deprecated to my knowledge however as you mentioned it is unfortunately undocumented. I can give a quick overview of `registerPlugin` which should definitely still work.

So in order to get your code to load into the player, it must be set up in the config block which is passed to your `setup` code, example below: 
```
{
  ...other jw config here...
  "plugins": {
    "path/to/your/plugin/file.js": {...plugin specific config (see below)...}
  }
}
```

This code will reach out to the path you gave it to download the JS and execute. In that JS file you must use `registerPlugin` to actually attach it to the player. A simple initiallzer might look like:

```
function initPlugin(playerInstance, pluginSpecificConfig, pluginSpecificDiv) {
  /**
    player instance: the instance of the player api the plugin is being registered with
    pluginSpecificConfig: the config block passed above in the setup call
    pluginSpecificDiv: a div created in the dom specifically for this plugin. you can use this or manipulate the dom within your plugin code
  */

  // Your plugin code here
}

const registerPlugin = window.jwplayerPluginJsonp || window.jwplayer().registerPlugin;
registerPlugin('my-unique-plugin-name', '7.0', initPlugin);
```

Apologies for this being undocumented, hopefully this is something we can patch up in the near future. Does the above make sense? Let me know if you have any additional questions.

**Comment by kvonspiczak** [comment]
hey @jnatalzia thank you for the reply! I'll look into the snippet you posted and try to get some basic plugin registered. Do you think my usecase with appending some HTML inside the player would work with a plugin? Basically I want to show a popup or similar (no ads, just related information to the spot in the video) e.g when reaching certain time in the video timeline.

**Comment by jnatalzia** [comment]
Yeah I think a plugin is a perfect setup for that. I recently did something similar with a custom element
```
// player api can be taken from the initializer
playerAPI.on('ready', () => {
    playerAPI.getContainer().appendChild(childElement);
});
```

**Comment by kvonspiczak** [comment]
awesome, i'll try experimenting with this then. is it just that registerPlugin call thats not documented, or is there more that I have to find out by experimenting (I mean the plugin development part of the API)

**Comment by jnatalzia** [comment]
Everything else _should_ be available in the developer docs in terms of api methods and events to listen to to build your plugin functionality.

**Comment by kvonspiczak** [comment]
alright, thank you for your help!

**Comment by kvonspiczak** [comment]
one more question: i'm getting error 305000 with the code you provided: https://developer.jwplayer.com/jw-player/docs/developer-guide/api/errors-reference/#305000
my console.log inside initPlugin is executed though. can i just ignore that message?
