### ISSUE TITLE
On mobile and portrait mode, full screen should rotate to landscape mode

### ISSUE THREAD

**Issue by Poopooracoocoo** [jwplayer/jwplayer#3488]
### Expected Behavior
 Video will play in landscape and fullscreen
### Actual Behavior
Video plays in full screen in portrait
### Steps to reproduce

1. Open a demo video in Chrome on a phone
2. Tap on full screen 

### Environment

- *Samsung Galaxy S5*
- *Android | 6.0.1*
- *Chrome | 77*
- *8.10.3 | url*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by karimMourra** [comment]
Hi @Poopooracoocoo , thank you for submitting this request. Could you please clarify the expected behavior ? Are you proposing that after tapping fullscreen, and subsequently rotating the device to landscape, the video should be displayed in landscape ?
Or are you proposing that after tapping fullscreen, the video should go to landscape regardless of the device's orientation ?

**Comment by Poopooracoocoo** [comment]
Hey @karimMourra

I'm proposing the latter. It should go to landscape after tapping full screen regardless of the phone's orientation. This behaviour happens with Chromium and Firefox's native players

**Comment by Poopooracoocoo** [comment]
@karimMourra 

https://bugs.chromium.org/p/chromium/issues/detail?id=326572

**Comment by aliciahurst** [comment]
Hi @Poopooracoocoo. I'm the product manager of the web player. Thanks for submitting this issue. If we rotated it to landscape regardless of the the phone's orientation, how would a viewer enforce portrait, if that's what they want?

**Comment by Poopooracoocoo** [comment]
Hey @aliciahurst! tysm for responding!

I think Chrome's reasoning was that the user can view the video in portrait by not pressing full screen like the YouTube app. The Chromium issue has a lot of cool stuff :)

**Comment by Poopooracoocoo** [comment]
hey um @aliciahurst 

anything on this?

**Comment by aliciahurst** [comment]
Hi @Poopooracooco,  sorry for not replying soon. We'll take this into consideration for a future release, but aren't going to take it up at this time. Thanks once again for the feedback!

**Comment by Poopooracoocoo** [comment]
idk how to remove the answered label but the maintainer said that they'll take it into consideration for a *future release*. that ain't forever (even if it sounds like it lol)

**Comment by Poopooracoocoo** [comment]
@aliciahurst Why was this closed? 

This issue is still relevant. The YouTube mobile site now uses a custom player and still auto rotates for horizontal content just like the YouTube app does. People have reported issues on Fenix (Firefox Preview on Android) and Focus (also Firefox) saying that fullscreen is "broken" because Firefox doesn't have this behaviour. 

i can't believe it's been MONTHS. September. holy cow

**Comment by jnatalzia** [comment]
Hi @Poopooracoocoo - Apologies for any frustration you're experiencing, however this issue is not a priority for our team at the moment. We use the GH issues to triage requests and bugs and then migrate them to our internal tracking board. As a result, resolution/closure of an issue is often based on our internal priorities and roadmap. We won't be reopening this issue for the time being, but will be sure to reach out in the event we see a rise in priority for this particular change.

Thanks as always for your input!

**Comment by Poopooracoocoo** [comment]
@jnatalzia thank you so much for the response. I was wondering about this each time I used JW Player on my phone.

A lot of GitHub repos leave issues they want to tackle at one point, even if far away, open. Why close it? It means that other people who may want to solve it may not see it and results in duplicate issues. I may have misunderstood and perhaps you guys won't be implementing this although I think I understood correctly. 

I'm so curious as to why it's such a low priority issue.

**Comment by jnatalzia** [comment]
> A lot of GitHub repos leave issues they want to tackle at one point, even if far away, open. Why close it?

We have decided to use our internal tracking system as the source of truth rather than GH issues. Closing out issues that we have triaged helps us to maintain a clean slate in the repository. While this does remove a layer of visibility in the OSS space, we need the clarity to help track our work and roadmap properly.

> I'm so curious as to why it's such a low priority issue.

While this issue may seem like something that should be attended to, due to the vast nature and number of requests and changes that we deal with, it's important to prioritize properly against everything we're looking to accomplish. This is another difficulty of tracking our roadmap internally in that the visibility of what we are working on is lowered.

**Comment by Poopooracoocoo** [comment]
That answers so many questions. I wish that were in the README.

**Comment by Poopooracoocoo** [comment]
@jnatalzia Hey Joe. It's been over a year. Is this finally on your roadmap?

**Comment by Poopooracoocoo** [comment]
@jnatalzia Was this implemented or added to the roadmap? Just following up on a bunch of my old issues.
