### ISSUE TITLE
Minimum buffer amount untenable in most instances in the wild.

### ISSUE THREAD

**Issue by bashpr0mpt** [jwplayer/jwplayer#3568]
### Expected Behavior

Be able to watch a video. I'm on a 100 megabit link and can stream anything, as long as it's not JWplayer.

### Actual Behavior

Buffer wheel every 1-2 seconds.

### Steps to reproduce

1. Be shitty web admin.
2. Not know how to setup min buffering.
3. Set it to 1 second.
4. Make everyone's life hell and JWplayer synonymous with unviewable content.
5. Make people file a bug report hoping JWplayer will set a minimum buffer amount to 5% of the video, to avoid bottlenecks and their product being associated with having a bad day.

### Environment

All.

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by jnatalzia** [comment]
Hi @bashpr0mpt, if I'm reading your issue correctly, it's a problem with the setup of the player and not the player code itself. We are generally not responsible for the way in which our player is configured and it would be untenable to create safeguards for each way we allow the player to be configured.

If I've misunderstood your question, please do let me know, otherwise I'll be closing this out. Thanks!
