### ISSUE TITLE
JW Player Warning 334001

### ISSUE THREAD

**Issue by graphem** [jwplayer/jwplayer#3585]
We have a live streaming with HLS and once in a while we get these warning:

JW Player Warning 334001

And the player freeze. Version of player is 8.12.2

JW player documentation doesn't offer any info on this warning.

**Comment by mamaddox** [comment]
Hey @graphem 
I am assuming something like this is what you are referring to:
![Screen Shot 2020-01-30 at 3 27 30 PM](https://user-images.githubusercontent.com/26205421/73487494-1de4f400-4375-11ea-8dc6-c29204728833.png)

All this means is that a non-fatal error has occurred so a warning was triggered. This was recently added so it hasn't made its way into our documentation yet. 

However, if you open up your console and expand the warning object printed below it, you can get a bit more information about it.

Also, in this case, this 334001 warning is close to the [234001 error](https://developer.jwplayer.com/jwplayer/docs/jw8-player-errors-reference#234001) denoting an HLS playback stall, which is probably what happened.

**Comment by graphem** [comment]
Ok thanks we will look into it

**Comment by ggwicz** [comment]
Hey @graphem, any news on this issue? JWPlayer 8 is still reporting non-existent error codes of `334000` and `334001`

**Comment by mamaddox** [comment]
Hi @ggwicz,
Sorry for the confusion. Unfortunately, it looks like our docs have still not been updated.

For the time being, if you see codes in the format 3xx xxx, these are warning codes and not error codes. Sometimes, they are in fact related to 2xx xxx error codes. For example, the 334001 warning code is related to the [234001 error code](https://developer.jwplayer.com/jwplayer/docs/jw8-player-errors-reference#234001), which means that HLS playback has stalled because not enough media has loaded.
I know this is not ideal, but as a general rule of thumb, you can look for the 2xx xxx error code counterpart (replace the leading 3 with a 2) to these warning codes to find out what they mean.

I'll tag this issue when the docs get updated.

**Comment by mamaddox** [comment]
Hi @graphem and @ggwicz,
Our docs have now been updated to reflect these new warnings. If you have further issues, please open a new ticket.
Here is a link:
https://developer.jwplayer.com/jwplayer/docs/jw8-player-errors-reference#section-media-playback-hls-js-warning

Thanks!
