### ISSUE TITLE
ADA Compliance -- Need to Tab Twice to Leave Player Scope

### ISSUE THREAD

**Issue by waltertschwe** [jwplayer/jwplayer#3603]
### Expected Behavior

Tab to JW Video Player and then tab again to leave the player scope.

### Actual Behavior

Tab to JW Video Player (highlights player), tab again highlights play button and then tab again to leave the player scope.

### Feature ?

The tabindex on the player and the play button are both set to zero.  This requires the user to have to tab twice to leave the player scope.  Are there additional features the user has access to when scoped on the player and not the play button? Is this to let the user access the player controls before starting the video?

**Comment by robwalch** [comment]
Hi @waltertschwe, Thanks for filing this issue.

The player and it's controls consist of multiple inputs, each of which is tab-able. This is to allow not just control of each button, but also screen-reader support.

Can you point out how this breaks ADA Compliance? Also what would be the correct tab indexes or ways to focus controls in the player once tabbed onto the player?

**Comment by aliciahurst** [comment]
Hi @waltertschwe, I'm the product manager of the web player, and to echo Rob, thanks for submitting this issue.

I maintain our VPAT, and I have a guess of what you're referring to, which is [bypass blocks](https://www.w3.org/TR/2007/WD-UNDERSTANDING-WCAG20-20071211/navigation-mechanisms-skip.html)? Can you confirm, or was there another WCAG criteria you meant? 

We could totally fix it for the idle screen because like you said, focusing on the whole player and the play icon are the same functionality. 

I've long wondered though what the best practice is once the player is in the play state, because there the whole control bar is visible, and I'm not sure what action we'd add in order to tab into it were we to allow it to be bypassed. I don't think the bypass block criteria was designed with a video player in mind. Do you have any opinions on the matter?

**Comment by waltertschwe** [comment]
@robwalch @aliciahurst Thanks for taking a look at this. After digging further the issue occurs because we have an image overlay hiding the built in play button.  When I remove the overlay it looks like this: 
![img_overlay](https://user-images.githubusercontent.com/618111/75796322-7840ee00-5d41-11ea-9770-f347ee59c30e.png)

We could simply set display none on the play button built in icon.  It's not ideal, but a possibility for us. During player initialization is there a way to set the `tabIndex` to -1 for the play icon and/or the video?  I've gone through the API documentation but didn't find anything.

@aliciahurst Like you said the whole player and the play icon have the same functionality.  I think the ideal behavior would be for the entire player to have a `tabIndex` of 0 and the play button by default to have a `tabIndex` of -1. To be able to control this via the API would be an added bonus if this doesn't exist. Thanks!

**Comment by aliciahurst** [comment]
Hi @waltertschwe, sorry it has taken so long for us to respond. I have a bug ticket in our backlog for this, and we do want to prioritize accessibility issues later this year. That said, I don't have a timeline to fix this exact issue and am unsure if/how we will. I'm going to close it out for now. 

We recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible, so in the future, I ask that you please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team. You'll be in great hands with them, and get a reply and support within a few business days. We also have better mechanisms there to inform you when we act upon your issue. Thanks for submitting!
