### ISSUE TITLE
[Feature request] Loading subtitle (srt/vtt) from file and/or URL (subtitleLoader)

### ISSUE THREAD

**Issue by hossam-magdy** [jwplayer/jwplayer#3656]
Sample screenshot of the feature:

![Screenshot from 2020-04-10 12-45-29](https://user-images.githubusercontent.com/17128077/78985623-8d235500-7b29-11ea-98f5-c3f95f33338a.png)

And regarding interface it can be added to the [setup options](https://developer.jwplayer.com/jwplayer/docs/jw8-player-configuration-reference#section-setup-options), like:

```ts
const player = jwplayer('player').setup({
    file: 'LINK_TO_YOUR_FILE.mp4',
    subtitleLoader: true // or possibly { fromFile: true, fromUrl: true }
});
```

**Comment by robwalch** [comment]
Hi @hossam-magdy,

A complete setup with side-loaded tracks looks like this. I point this out because, if we were to implement a feature like this, we'd need to decide if the setting to lazy load tracks is on the individual track level or top-level impacting all side-loaded tracks:

```js
jwplayer('player').setup({
    playlist: [{
        file: '//domain/path/source.mp4',
        image: '//domain/path/image.jpg',
        tracks: [{
            file: '//domain/path/track.vtt',
            label: 'English',
            kind: 'captions'
            // what kind of flag here (or at the top level) would direct the player
            // to load this track only after it is selected?
        }]
    }]
    // or here?
});
```


While `jwplayer` loads all side-loaded tracks once a playlist item becomes active (this includes "chapter", "thumbnail" and "captions"/"subtitle" tracks), there could be a directive similar to what you suggest to only load "captions"/"subtitle" track once selected. I don't think we'd change the UI for this. We would have to consider pausing playback until the track is loaded when changing to a track that has not loaded. 

Thanks for the suggestion. Please include why this feature is important to you and include the [Full Issue Template](https://github.com/jwplayer/jwplayer/issues/new) submitting
"Steps to reproduce" with a user story or list of acceptance criteria.

**Comment by hossam-magdy** [comment]
Thanks for your comment @robwalch !

Actually the main feature I was referring to is not about a predefined URL in the API/interface level but rather to explicitly include the UI button/option for the user to load subtitle. I only showed an example how it possibly can be in the interface, because I read a [question](https://github.com/jwplayer/jwplayer/issues/3518#issuecomment-551312130) in a similar closed [request](https://github.com/jwplayer/jwplayer/issues/3518#issuecomment-550404487) about further clarification how it can be in the interface level.

**Comment by robwalch** [comment]
For VTT text tracks embedded in HLS and DASH streams, the vtt is not loaded unless the track is selected in the current menu. For VTT text tracks in the API setup config, we always load them on "playlistItem". So in fitting with your request, only loading them upon selecting the captions track would be something we could do.

Your suggestion is appreciated, but we would not make it optional or change the UI.
