### ISSUE TITLE
VR/360/Cardboard Button just on toggle fullscreen

### ISSUE THREAD

**Issue by alegroSandermann** [jwplayer/jwplayer#3663]
### Expected Behavior
At https://www.jwplayer.com/developers/web-player-demos/360-video/
Show the VR Button to enter full immersive mode

### Actual Behavior

The button just appears if I set the player to fullscreen and back

### Steps to reproduce

1. Open the URL
2. Start the player
3. Set fullscreen
4. Exit fullscreeen
5. The VR button apperas

### Environment

- oculus quest/go, pico g2 4k
- android | 7 / 8
- firefox reality | latest
- JW Player version 8.13.4

**Comment by jnatalzia** [comment]
Hi @alegroSandermann , thanks for the report - we've confirmed this issue internally and have slated it to be fixed in an upcoming patch.

**Comment by denschub** [comment]
Hi there! I work at Mozilla, and we've also ran into this issue due to reports from our users. Since you already appear to be working on a fix, I won't debug further, but if you need any help or if you think there needs to be a change inside Firefox to make this happen, please let me know! Feel free to ping me on GitHub or reach out via eMail to `dschubert@mozilla.com`, I'm happy to assist!

**Comment by jnatalzia** [comment]
Hi @denschub ! Thanks for reaching out. We will certainly let you know if we need assistance 😄

**Comment by robwalch** [comment]
The VR plugin depends on webvr-polyfill which is no longer compatible with Promise based requestFullscreen in Chrome. Our player also does not use Promise based requestFullscreen which results in incorrect handling of fullscreen state and request/responses.

The webvr-polyfill is not actively maintained because the spec it implements has been deprecated:

https://developer.mozilla.org/en-US/docs/Web/API/WebVR_API
https://github.com/immersive-web/webvr-polyfill/

WebVR has been replaced by WebXR:

https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API
https://github.com/immersive-web/webxr-polyfill - Connect to preview 

Porting the VR code over to restore the functionality we used to have is not trivial. I've tried us following this migration guide from WebVR to WebXR and fell short. It's more than a days work and that time we need to spend elsewhere.

 https://github.com/immersive-web/webxr/blob/master/webvr-migration.md

I went ahead and tried to do some of the porting, but it broke rendering. See:
https://github.com/jwplayer/jwplayer-commercial/compare/bugfix/webvr-to-webxr
Either way it is unlikely Chrome will allow access to orientation data without hosting over SSL (https) and possibly presenting a dialog to the user to allow access.

The VR code is part of our private code base, but it used to be in its own plugin project. Maybe we can bring that back an open-source it for anyone interested in it.

**Comment by robwalch** [comment]
https://support.jwplayer.com/articles/how-to-embed-360-and-vr-videos

> JW Player will no longer support 360 or VR video functionality beyond October 18, 2020. All player versions starting with 8.18.0 will ignore legacy 360 and VR settings.
