### ISSUE TITLE
Can't find max resolution for 360 top/bottom video file

### ISSUE THREAD

**Issue by alegroSandermann** [jwplayer/jwplayer#3664]
What is the max resolution?
I found nothing in the documentaion.
This page https://www.jwplayer.com/developers/web-player-demos/360-video/ says: 4k resolution.
But what does this mean if I have a top/bottom 1:1 resolution?
Normally 4k resolution means 4096x2048.
I tried 4096x4096. The video plays with no errors, the sound is playing but I have a black screen.

**Comment by robwalch** [comment]
Hi @alegroSandermann,

Generally we are limited by the GPU’s max texture size. 4096 won’t work everywhere, but 2048 is pretty safe. 

There could be other factors across devices, os and browsers, so please include these details with versions as well as any relevant console warning or error messages, so that we can help troubleshoot.
