### ISSUE TITLE
jwplayer 8.14.0 scrollbar jumps on some specific container dimensions

### ISSUE THREAD

**Issue by kapouer** [jwplayer/jwplayer#3696]
### Expected Behavior

no scrollbar should be shown, or at least not hesitating like that.

### Actual Behavior

A scrollbar keeps appearing and disappearing.
EDIT: i tried to capture it but failed, so i removed it.

### Steps to reproduce

1. embed a jwplayer 8.14.0 player in a width:100% height:0; padding-bottom:56.52% container
(or whatever value)
2. open in chrome, resize window slowly. It helps to play with the page magnification (zoom).

### Environment

- imac 2011
- Debian 5.6.14-1 (2020-05-23) x86_64 GNU/Linux
- reproduced on chrome 74 to chrome 83, on linux and windows
- jwplayer 8.14.0

**Comment by kapouer** [comment]
This can be reproduced there for example, with a page zoomed at 90%, after the advertisements.
https://sport24.lefigaro.fr/football/transferts/actualites/en-direct-foot-mercato-rumeurs-transferts-jeudi-11-juin-1004312

**Comment by kapouer** [comment]
And some users have reported to see this issue even with a non-zoomed page.

**Comment by frob** [comment]
I am seeing a very similar issue with 8.18.7 It is getting manifest by the controls jumping up and down in the chrome browser only.

Seems like the video isn't always effecting the height of the container.

**Comment by aliciahurst** [comment]
Hi @frob, I'm the product manager of the player, and wanted to say that I'm sorry we're taking so long to reply to you. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible, which is why I'm going to close out this issue, and ask that if it still persists, you please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team, led by @SageBrushes. You'll be in great hands with them, and get a reply and support within a few business days. Thanks for submitting!
