### ISSUE TITLE
Floating/Float-on-Scroll player pauses in Safari after volume adjustment

### ISSUE THREAD

**Issue by seanmaisch** [jwplayer/jwplayer#3704]
### Expected Behavior

Adjusting the volume on a JW Player, scrolling down to trigger a floating video player, will allow the video player to continue playing interrupted. Scrolling back up to remove the floating state of the video player will continue playing the video seamlessly.

### Actual Behavior

Adjusting the volume on a JW Player, scrolling down to trigger a floating video player on Safari, forces the video player to pause and remain paused until the user resumes the video. This is the case when the video player is both floating and removed from its floating state.

### Steps to reproduce

1. Open Safari.
2. View a JW Player with “floating”: { "dismissible": false } enabled within the setup.
2. Adjust the volume on the video player (mute, unmute, adjust levels, anything really…)
3. Scroll down to trigger Float-on-Scroll functionality / `jw-flag-floating`.
4. Observe that the video has now been paused by Safari.

### Environment

- Hardware: MacBook Pro (Retina, 15-inch, Mid 2015)
- OS: macOS Mojave Version 10.14.5 (18F203)
- Browser: Safari Version 12.1.1 (14607.2.6.1.1)
- JW Player Version: 8.16.0
- URL: https://www.ballertv.com/streams/sunshine-state-preseasn-classic/american-heritage-vs-north-broward-prep

**Comment by seanmaisch** [comment]
I'd like to follow-up on this. After disabling **Automatically pause when player is not viewable**, the issue seems to be resolved. Not sure what this has to do with the volume being adjusted, or if this was fixed/patched in some other way.

![image](https://user-images.githubusercontent.com/2513432/85466476-e151a900-b55e-11ea-8b50-ccaf2b57c67f.png)

Is it possible that when the volume gets adjusted, then scrolling occurs, that the player "leaves" the Safari viewport and is forced to pause somehow?

I'm really at a loss for what's causing this, but I will gladly provide you with more details regarding player configuration so you can reproduce if you'd like to address this issue for other users.

**Comment by robwalch** [comment]
Hi @seanmaisch,

It's a little unclear what interacting with the volume UI has to do with the issue. This bug is only reproducable when you interact with the player before floating?

If [`autoPause` based on `viewability`](https://developer.jwplayer.com/jwplayer/docs/jw8-player-configuration-reference#section-auto-pause) is enabled, then the player should pause when it is not in the browser viewport. If you're seeing this auto pause behavior kick in when the player transitions to a floating state, and it's only momentarily hidden while transitioning, that's something we can look at fixing.
