### ISSUE TITLE
Arrow-Down icon in related-shelf is overflowing in fullscreen-mode on desktop browsers

### ISSUE THREAD

**Issue by manuelroth** [jwplayer/jwplayer#3730]
### Expected Behavior

The arrow-down icon in the related-shelf should be fully visible like it is in inline-mode. The following screenshot shows how it looks in inline-mode:

<img width="250" alt="arrow-down-icon-not-overflowing-in-inline-mode" src="https://user-images.githubusercontent.com/1810384/90896276-a388c980-e3c3-11ea-8f5f-06e939e66fa3.png">

### Actual Behavior

When the video player is in fullscreen-mode the arrow-down icon in the related-content-shelf is overflowing. The following screenshot shows how the icon is overflowing:

<img width="330" alt="arrow-down-icon-overflowing-in-fullscreen-mode" src="https://user-images.githubusercontent.com/1810384/90897329-4261f580-e3c5-11ea-9117-1ed23e8b83cd.png">

### Steps to reproduce

1. Go to https://www.nzz.ch/video/nzz-format/asiens-fette-jahre-macht-wohlstand-dick-ld.1501317 (uses the standard jw-player, no custom CSS is being applied) and play the video on a Desktop Browser (on mobile a different UI is shown for related content)
2. Go in fullscreen-mode by clicking on the icon in the bottom right corner
3. Click on "Weitere Videos" in the bottom left corner and see how the arrow-down icon is overflowing in fullscreen-mode

### Environment

- MacBook Pro 13-inch
- macOS 10.15.6
- Google Chrome 84.0.4147.135 / Safari 13.1.2 / Firefox 79.0
- JW Player 8.17.1

**Comment by aliciahurst** [comment]
Hi @manuelroth, I'm the product manager of the player, and wanted to say that I'm sorry we're taking so long to reply to you. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible, which is why I'm going to ask that in the future when you find a problem, please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team. You'll be in great hands with them, and get a reply and support within a few business days, and there we have tracking in place to be able to notify you when your issue is resolved. 

For this particular bug, thanks for pointing it out! We never noticed it before. It's very slight. I've filed a bug in our backlog but I don't have a timeline for you right now. Going to close this out for now but thank you for submitting it!
