### ISSUE TITLE
Localization custom button 

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#3741]
There are no options for user buttons to fully locate the player.
An example of how this should work:

```
# addButton(img, tooltip, callback, id, btnClass)

jwplayer().addButton(<svg/>, 'Download', ()=>{}, 'dl-button', '')

```

```
"intl": { 
    "pl": {
      "customButton ": {
        "dl-button": "Pobierz"  // id button 
      }
   "de": {
      "customButton ": {
        "dl-button": "Herunterladen"  
      }
    }
  }
});
```

**Comment by robwalch** [comment]
@mtoczko I'm not sure I understand what you mean by "locate the player". Do you mean localize the button label? that's a good suggestion.

Please describe how your example works to complete this feature request (support for custom button id entires in `intl` block).

**Comment by mtoczko** [comment]
When you add a button, set  id:`dl-button` and default label `Download`. If there is no translation for this button displays the default label
`jwplayer().addButton(<svg/>, 'Download', ()=>{}, 'dl-button', '')`

For supported languages in the Custom button section, for the identifier `id` we assign a label in that language.
```
"intl": { 
    "pl": {
      "customButton ": {
        "dl-button": "Pobierz"  // id button 
      }
...
```
I don't know how to describe it more .

**Comment by aliciahurst** [comment]
Hi @mtoczko! I'm the product manager of the player, and wanted to say that I'm sorry we're taking so long to reply to you. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible, which is why I ask that in the future, please [submit issues](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team. You'll be in great hands with them, and get a reply and support within a few business days. We also have mechanisms in place to get back to you if we act on your request. 

I'm concerned with the complexity of the ask since we localize the player on setup, and the add button method can be used any time after that. That method gives a great deal of flexibility so what I would recommend there would be some custom logic, something like, in pseudocode: if html lang="en" then add button with the word "Download," if html lang="de" then add button with the word "Herunterladen". You can further optimize that with some variables. This is what I recommend because it's practically as many characters/lines as you'd add via JSON, and certainly less code than we'd need to add to support it out of the box. 

Thanks for submitting!
