### ISSUE TITLE
Set current quality on `ready` event

### ISSUE THREAD

**Issue by Hadrien-DELAITRE** [jwplayer/jwplayer#3758]
### Expected Behavior

Sets correctly the current quality to the given value.

### Actual Behavior

Doesn't set the current quality.

### Steps to reproduce

1. Nothing particular to do, just call the `setCurrentQuality` with `0` as index when `ready` player event is triggered.

### Environment

- Windows 10
- Chrome/FF
- 8.17.7

----------------------------------------------------------------------------------------

It seems that since this commit 0622d8ee5630, I can't call the `setCurrentQuality` from the `ready` player event. In that case, `qualityMenu` seems to not defined and it throws at this line :
https://github.com/jwplayer/jwplayer/commit/0622d8ee5630cb8b0e5ebcfff33104f685c65b0d#diff-a5e74a0885488d006501fb2f05af79bc4b77f7809a774e1c4dac6f24692fc485R78

My workaround is to call the `setCurrentQuality` only one time when `levels` event is triggered in order to initialize the quality as I want.

I don't know if there is another way to initialize the quality in a different way when a `localStorage` value of `jwplayer.quality` already exists.

Thanks you!

**Comment by robwalch** [comment]
> I don't know if there is another way to initialize the quality in a different way when a localStorage value of jwplayer.quality already exists.

`setCurrentQuality` will only work after the '"levels"' event. If you want the player to make a manual quality selection upon loading an HLS stream, add a `bitrateSelection` value to your config. The player will pick the quality closest to this bitrate and remain in manual quality selection mode, rather than auto. If you don't the bitrate but know the level label assigned by the player (ex "720") you can try setting `qualityLabel` instead, but `bitrateSelection` is preferred since labels can change between streams. Set these values to null at setup and clear their corresponding local storage value to return to auto mode.

**Comment by Hadrien-DELAITRE** [comment]
OK thanks for your reply.
In our case we don't use HLS stream so it's a good usage to set the current quality when `levels` event occurs 👍 

Best regards.
