### ISSUE TITLE
Black background (background-image:url) due to unescaped slashes 

### ISSUE THREAD

**Issue by torgospizza** [jwplayer/jwplayer#3760]
### Expected Behavior
When Casting a video to Chromecast, the thumbnail image should appear as the background in the cast sender player.

### Actual Behavior
After Casting the video, the thumbnail is replaced by a black background. In the rendered source HTML, the div.jw-cast has an inline CSS declaration for `background-image:url` which has a munged version of the URL found in the jw-preview div. 

### Steps to reproduce

1. In JW Platform, pull up a Player with the example video with Cast enabled.
2. Click the "Cast" icon.

### Environment

- Lastest Chrome on MacOS 10.15.7
- Problem is apparent in JW Player 8.17.7 and 8.17.4. It can be reproduced using self-hosted and cloud-based players.

**Comment by torgospizza** [comment]
Here is a screenshot of this behavior after clicking "Cast":

<img width="1691" alt="Screen Shot 2020-10-19 at 10 17 29 PM" src="https://user-images.githubusercontent.com/294596/96623322-0ca39500-12c0-11eb-8b2c-fd1c5bc85ea1.png">

**Comment by aliciahurst** [comment]
Hi @torgospizza, I'm the product manager of the player, and wanted to say that I'm sorry we're taking so long to reply to you. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible, which is why I'm going to close out this issue, and ask that if it still persists, you please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team, led by @SageBrushes. You'll be in great hands with them, and get a reply and support within a few business days. Thanks for submitting!
