### ISSUE TITLE
Can the `type` in `jwplayer.setup()` be made case insensitive?

### ISSUE THREAD

**Issue by sharang-d** [jwplayer/jwplayer#3853]
### Expected Behavior

"MOV" when passed as `type` in `jwplayer.setup()` makes the video play.

### Actual Behavior

"MOV" when passed as `type` in `jwplayer.setup()` causes an error.

### Steps to reproduce

Currently, this works:
```javascript
jwplayer('player').setup({
    file: 'https://filesamples.com/samples/video/mov/sample_960x540.mov',
    type: 'mov'
});
```

But, this does not:
```javascript
jwplayer('player').setup({
    file: 'https://filesamples.com/samples/video/mov/sample_960x540.mov',
    type: 'MOV'
});
```

(Note: Ideally, the file^ would be without an extension but I don't have one that is publicly accessible so I'm using this)

Can the library make a change such that all types are lower-cased automatically? Or are there some cases where the case matters? (I don't think it does going by the acceptable values at https://developer.jwplayer.com/jwplayer/docs/jw8-player-configuration-reference#media)

### Environment

- MacBook Pro (15-inch, 2018)
- macOS 11.2.3
- Firefox developer Edition 88.0b9 (64 bit)
- JW Player version 8.20.2: https://cdn.jwplayer.com/libraries/lqsWlr4Z.js (From https://github.com/jwplayer/web-player-demos)

**Comment by robwalch** [comment]
Hi @sharang-d,

Since the player accepts a list of documented types which are all lowercase, you should use one of those values.

If you are unsure about the input you are providing to jwplayer, apply `toLowerCase()` to your type values in the playlist sources. We do not wish to add this additional code to the player since the types are well documented and this should be easy to do on your end.

**Comment by sharang-d** [comment]
Yeah, I did lowercase it after I found out but it was surprising that the library didn't do it as the case does not really matter. Closing as the API seems fine to you.
