### ISSUE TITLE
Lighthouse punishes multiple players

### ISSUE THREAD

**Issue by vinkodlak** [jwplayer/jwplayer#3855]
Hello guys,

Just saw that I have 100% score on accessibility tab in lighthouse audit, but only when there is one video on the page.
If I add 2nd one, score falls to 94%, because of unique ARIA-ID rule:

![image](https://user-images.githubusercontent.com/24816470/115592704-8af9e780-a2a1-11eb-9201-ae40a47c6191.png)

Problem is that each player adds own controls+setting+other elements, and some of them have #id, like
jw-shortcuts-tooltip-explanation,
jw-settings-menu

Could you target those elements in your HTML+script somehow different than with #id and/or completely remove it?

For my case, only those two are problem, player.setup() only receives playlist info, other settings are default ones...

i see that #jw-settings-menu alsoo has a class with the same name, that guy could be targeted by classname and id attr left out,
jw-shortcuts-tooltip-explanation would need classname because doesn't have one.

**Comment by robwalch** [comment]
Hi @vinkodlak,

Thanks for submitting this issue. 

It's a shame we use non-unique ids in player control elements this way. We should have included the player id as part of these child element ids.

So if your player id (and its container) was #player1 these elements would have `-player1-` as part of these ids. Then the other player which would have a different id like #player2 would have a menu with id `#jw-player2-settings-menu` (for example. We have to be careful about making such a change since some users may be using the existing ids for styling or other changes with single players, and not expecting a name change in an upcoming release.

**Comment by vinkodlak** [comment]
Oh, yeah sure, that would be breaking change for those users.

Could you make it so it depends on some .setup({usePlayerIdForChildNodes: true}) configurable option, that would default to false and not break anything to those users?
