### ISSUE TITLE
Erro on windows 7

### ISSUE THREAD

**Issue by MarcosSouza2004** [jwplayer/jwplayer#3859]
### Expected Behavior
Play the video

### Actual Behavior
"Sorry the video player failed to load"
![image](https://user-images.githubusercontent.com/76596575/116286058-305f0080-a765-11eb-9842-df1826916c1f.png)

### Steps to reproduce
Unknow 

### Environment

- *hardware | device* Intel i3, 8gb ram, SSD
- *operating system | version* Windows 7
- *browser | version* Chrome, 90.0.4430.93
- *JW Player version | url* 8.20.2

----------------------------------------------------------------------------------------

**Comment by userzumi** [comment]
As far as I know, all Windows 7 users suffer from this problem, and they cannot play the video even though they're using any browser.
![image](https://user-images.githubusercontent.com/72013752/117540448-b159aa00-b039-11eb-8a1c-42110b699f5e.png)

**Comment by aliciahurst** [comment]
Hi @MarcosSouza2004, I'm the product manager of the player, and wanted to say that I'm sorry we're taking so long to reply to you. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible, which is why I'm going to close out this issue, and ask that if it still persists, you please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team, led by @SageBrushes. You'll be in great hands with them, and get a reply and support within a few business days. Thanks for submitting!

**Comment by guigonc** [comment]
@aliciahurst Would you consider reopening the issue so that investigate further. If necessary I can provide you more details to simulate it

**Comment by aliciahurst** [comment]
Hi @guigonc sorry I never replied, but please submit your issue by creating a support ticket and our support engineers can help facilitate the investigation. Thanks!
