### ISSUE TITLE
CLS on Mobile Player rotation

### ISSUE THREAD

**Issue by jascaldeira** [jwplayer/jwplayer#3866]
### Expected Behavior

No CLS on player rotation

### Actual Behavior

A lot of CLS on player rotation

### Steps to reproduce

1. Activate mobile emulator and DevTools on Chrome
> 1.1. CTRL + SHIFT + P
> 1.2. Show Rendering
> 1.3. Activate Layout Shift Regions
2. Enter in any JW Player
3. Pause the video
4. Rotate the device
5. See the blue areas, there is a lot of CLS there

### Environment

- Desktop
- Windows 10
- Chrome 90.0.4430.93
- 8.20.2

**Comment by aliciahurst** [comment]
Hi @jascaldeira, I'm the product manager of the player. I want you to get the help you need as fast as possible, which is why I'm going to close out this issue, and ask that you please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team You'll be in great hands with them, and get a reply and support within a few business days. Thanks for submitting!
