### ISSUE TITLE
SSL cert error on Windows

### ISSUE THREAD

**Issue by guigonc** [jwplayer/jwplayer#3873]
### Expected Behavior

Load the player

### Actual Behavior

The player is not loading with a error code 101102

### Steps to reproduce

1. Load a page with the player

### Environment

- Windows 7
- Chrome
- JW Player 8.17.7

I could spot that the error is happening due to some SSL cert issues for the following domains:

https://ssl.p.jwpcdn.com
https://prd.jwpltx.com
https://6ce137740fb440b4943f99ccaa015b81.js.ubembed.com

<img width="610" alt="Screen Shot 2021-05-11 at 18 19 07" src="https://user-images.githubusercontent.com/1074492/118649767-41c28800-b7ba-11eb-8f23-0de1f6c4bff0.png">

The error has been mentioned in a closed issue
https://github.com/jwplayer/jwplayer/issues/3859

**Comment by aliciahurst** [comment]
Hi @guigonc,  I'm the product manager of the player, and wanted to say that I'm sorry we're taking so long to reply to you. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible, which is why I'm going to close out this ticket and ask that you please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team. You'll be in great hands with them. Thanks for submitting!
