### ISSUE TITLE
Thumbnail preview/time tooltip goes beyond the edges of the player

### ISSUE THREAD

**Issue by roquez** [jwplayer/jwplayer#3879]
### Expected Behavior

![scr](https://user-images.githubusercontent.com/21342425/119402325-10c3e500-bcdd-11eb-9a7b-d1b442081252.jpg)

### Actual Behavior

![scr](https://user-images.githubusercontent.com/21342425/119395934-7e1f4800-bcd4-11eb-9a07-7299d290fd5c.jpg)

I noticed this happens only when the thumbnails in a VTT are in separate files, not a sprite sheet, eg:
```
WEBVTT 

00:00.000 --> 00:05.000
/assets/thumbnail_1.jpg

00:05.000 --> 00:10.000
/assets/thumbnail_2.jpg

00:10.000 --> 00:15.000
/assets/thumbnail_3.jpg

00:15.000 --> 00:20.000
/assets/thumbnail_4.jpg
```

You can also see the tooltip clipping when there is no thumbnails track provided:

![scr](https://user-images.githubusercontent.com/21342425/119402588-71ebb880-bcdd-11eb-929a-e1183eb137e9.jpg)

**Comment by aliciahurst** [comment]
Hi @roquez , I'm the product manager of the player, and wanted to say that I'm sorry we're taking so long to reply to you. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible, which is why I'm going to close out this issue, and ask that if it still persists, you please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team, led by @SageBrushes. You'll be in great hands with them, and get a reply and support within a few business days. Thanks for submitting!
