### ISSUE TITLE
Video moves at the top when playing in fullscreen mode on ipad/chrome browser

### ISSUE THREAD

**Issue by ankuraga1508** [jwplayer/jwplayer#3893]
### Expected Behavior

Video should remain in the center when it is played in the fullscreen on ipad in chrome browser

### Actual Behavior

Video moves at the top when playing in fullscreen mode on ipad/chrome browser

### Steps to reproduce

1. Open this link (https://www.jwplayer.com/developers/web-player-demos/ad-verification/) on chrome browser in ipad 14.2
2. Play the video
3. Go into fullscreen mode
4. Wait until the ad video completes
5. You will see buck bunny video playing but notice that video is shifted up. It should stay in the center.

### Environment

- ipad 14.2
- chrome 76.0.3809.123
- https://www.jwplayer.com/developers/web-player-demos/ad-verification/

Attached the video (https://user-images.githubusercontent.com/15721876/122614993-59a55a00-d04d-11eb-94c6-08e29926bfe2.mp4) to showcase the issue.

**Comment by aliciahurst** [comment]
Hi @ankuraga1508, I'm the product manager of the player, and wanted to say that I'm sorry we're taking so long to reply to you. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible, which is why I'm going to close out this issue, and ask that if it still persists, you please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team, led by @SageBrushes. You'll be in great hands with them, and get a reply and support within a few business days. Thanks for submitting!
