### ISSUE TITLE
Load percent when buffering

### ISSUE THREAD

**Issue by jazz1611** [jwplayer/jwplayer#3910]
### Expected Behavior
How can i make load percent when buffering at first playback or seek video?
### Actual Behavior
https://user-images.githubusercontent.com/1846222/128051107-88658505-4714-46d3-b92a-073eab130237.mp4
### Steps to reproduce
Not sure
### Environment
- Windows 10 20H1 64bit
- Firefox 90.0.2 (64-bit)
- *JW Player version | 8.20.2

**Comment by aliciahurst** [comment]
Hi @jazz1611, I'm the product manager of the player, and wanted to say that I'm sorry we're taking so long to reply to you. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible, which is why I'm going to close out this issue, and ask that you please (https://support.jwplayer.com/submit-support-case) to our fabulous technical support team. You'll be in great hands with them, and get a reply and support within a few business days. Thanks for submitting!

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@aliciahurst, are you able to provide the resolution to this problem? GitHub is usually considered to be superior to private support because all of the history is available.

**Comment by aliciahurst** [comment]
Hi! I don’t actually work at JW Player anymore, but support is indeed the
preferred way to get help. Thanks!
