### ISSUE TITLE
redirected video url gives 224003

### ISSUE THREAD

**Issue by mbassiouny33** [jwplayer/jwplayer#3940]
Hi there,

I have the following issue:
We had jwplayer play with a code like
```

	    jwplayer('sjwplayer').setup({

              file: 'http://example.com/files1/xyz.mp4', // or maybe file: 'http://example.com/files2/****.mp4',
	      title: '<h1>mp4 file player</h1>',
	      width: '100%',
	      aspectratio: '16:9'
	    });
```
Now problem is, backend link formats changed, and when you visit directly ( by putting url in web browser) `example.com/files1/xyz.mp4` you get redirected to  `s1.example.com/xyz.mp4` or `s2.example.com/xyz.mp4` and it works fine. But the problem is, this redirection confuses jwplayer and it gives 224003. Is there anyway around it?

### Expected Behavior
Video should play

### Actual Behavior

Video does not play, and the player gives 224003 error code.

### Steps to reproduce

1.modify url structure of backend server

### Environment

backend runs on Debian 10 and nginx.

Thanks in advance

**Comment by aliciahurst** [comment]
Hi @mbassiouny33, I'm the product manager of the player, and wanted to say that I'm sorry we're taking so long to reply to you. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible, which is why I'm going to close out this issue, and ask that if it still persists, you please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team. You'll be in great hands with them, and get a reply and support within a few business days. Thanks for submitting!

**Comment by mbassiouny33** [comment]
Seems support is only available for people with paid plans.
