### ISSUE TITLE
Multiple players with YouTube embeds on a single page do not initialize

### ISSUE THREAD

**Issue by wimlatour** [jwplayer/jwplayer#726]
Having multiple JW Players with YouTube embedded videos on a single webpage does not seem to initialize all videos well. The first player works, but all next players only initialize the JW Player skin and preview image, not the YouTube video.

While debugging the JW Player source I triggered this exception:

`There was an error calling back an event handler for "ready". Error: Cannot read property 'loaded' of undefined`

I think what happens is:
 - The first player triggers embedding the YouTube iframe_api and waits for it to load before initializing the video
 - Next players don't wait for the iframe_api (window.YT and window.YT.loaded) to be loaded

I have tested this with JW Player 7.0.3 and the latest versions of Chrome, Canary, Firefox and IE11:
http://wim.latour.nl/jwplayer/jwplayer7-multiple-youtube.html

What solves this issue (for now) is loading the YouTube iframe_api myself and initialize the JW Players in the `onYouTubeIframeAPIReady()` callback:
http://wim.latour.nl/jwplayer/jwplayer7-multiple-youtube-with-iframe_api.html

Tested with JW Player version: `7.0.3+commercial_v7-0-3.45.commercial.39321c.jwplayer.d015f3.analytics.1c4f4e.vast.19906c.googima.deb821.plugins.3891c4` as downloaded from https://dashboard.jwplayer.com/#/players/downloads

**Comment by robwalch** [comment]
Thanks @wimlatour,

We had a bunch of internal tickets related to this. Your test cases help to isolate the issue.

**Comment by jeepcreep** [comment]
hey there,

we're experiencing the same thing in our custom built internally used video CMS as of v7 (worked normally with v6), but there is no youtube provider setup involved here. one commonality might be that we do have multiple player setups on a single page... the strange behaviour however (first setup succeeds, consecutive fail with the above error message) is identical.

have you spotted a more common error so that our error will get fixed as well?

we have Ads edition for our company, currently v6 in production and v7 in testing - when can I expect v7.2 to be released?

best regards,
Nils Weber
Bauer Xcel Media Germany

**Comment by donato** [comment]
Hi @jeepcreep - we are working on hardening v7.2 right now. We are aiming to have a release by the end of the month.

**Comment by donato** [comment]
@jeepcreep @wimlatour - We decided to put this fix into the v7.1.5 patch so you can get it in your hands a little sooner.

http://p.jwpcdn.com/player/v/7.1.5/jwplayer.js

**Comment by jeepcreep** [comment]
thanks @donato , will test it shortly!

**Comment by slavanga** [comment]
Multiple Youtube videos work for me with v7.1.5.
Users of the hosted player have to switch to the staging release channel to use that version right now.
