### ISSUE TITLE
Video in player scales down smaller than the size of the player

### ISSUE THREAD

**Issue by kharri1073** [jwplayer/jwplayer#778]
@frandevinney and I have been debugging an issue with the jwplayer for some time now. It seems that when the player is less than 639px in width, a transform css property is added inline to the video tag. This produces a rather ugly letterbox around video content.

For example (player width 638px) - 
`<video x-webkit-airplay="allow" webkit-playsinline="" src="{video-url}" style="bottom: 0px; top: 0px; left: -1px; right: -1px; transform: scale(0.996875, 1); width: 640px; height: 360px;"></video>`

![embed_large](https://cloud.githubusercontent.com/assets/972280/10173999/6333201e-66b5-11e5-964b-e56d06e8eac6.png)

* * *
 
The transform scale gets greater and greater as the video player is further reduced (player width 400px) -
`<video x-webkit-airplay="allow" webkit-playsinline="" src="{video-url}" style="bottom: -67px; top: -67px; left: -120px; right: -120px; transform: scale(0.625, 0.627778); width: 640px; height: 360px;"></video>`

![embed_small](https://cloud.githubusercontent.com/assets/972280/10173987/4f24a336-66b5-11e5-868b-47833b9104c9.png)

* * *

We've worked around this issue by recompiling and sending a return before transformScale is set.

your code - https://github.com/jwplayer/jwplayer/blob/master/src/js/view/view.js#L739-L772

our work around - a174823d2dc4fe9b9a0a4f4cac5bcdf9895869cc

With this in place our video players no longer display in a letterboxed player.

![embed_new](https://cloud.githubusercontent.com/assets/972280/10174966/75ad357c-66ba-11e5-8fea-2c645834d8bf.png)
`<video class="jw-video jw-reset" x-webkit-airplay="allow" webkit-playsinline="" src="{video-url}" preload="metadata"></video>`

While we realize this is not a true fix, we're hoping that this issue could shed some light on this issue. We're currently browser testing and it looks like based on our needs we might go with this solution.

**Comment by robwalch** [comment]
@kharri1073 can you provide a test page along with steps to reproduce. We have a few responsive tests and haven't encountered this behavior.

There are also several ways to configure how the player and media within the player scale, so including your player setup would be very helpful.

We've looked into replacing the scale-mode code in jw7 with CSS object-fit, but the browser coverage just isn't there yet http://caniuse.com/#feat=object-fit 

Maybe object-fit'll do the trick for you. After we look at your setup we can maybe try one that disables transforms and lets you use CSS.

**Comment by kharri1073** [comment]
Thank you @robwalch. We have an old version of jw (v6.12) which is also affected. To test the letterboxed video, you can visit http://www.ora.tv/embed/0_vjup4bb6nbr. To test the our forked code, you can visit http://vpc-www-prod3.ora.tv/embed/0_vjup4bb6nbr.

We figured we would finally tackle this issue for preparation to upgrading our player to 7.1.

This behavior only occurs with `<video>` tags and not `<object>` tags.

**Comment by robwalch** [comment]
@kharri1073 I'm getting the Flash player with that first url in Safari and Chrome because you're setting `primary` to `"flash"`. If you turn that off, we should be able to look at the problem in Safari which can play your HLS stream natively.

You're not specifying a stretching option in your config. The default is uniform so that's fine. "uniform" seems to be the behavior you want. That would be the same as `object-fit: contain;` or `background-size: contain;`. We have not seen this issue in 7 or 6 so I'd try to make sure it's not related to your player container or maybe something specific to Safari which is quirky when it comes to transforms.

This shouldn't stop you from moving the jw7. If anything I'd hurry up and make the change. You'll find the code in stretch.js was modified quite a bit in jwplayer 7 to take advantage of our use of CSS in the player. We also continue to do the stretching in Flash in 7 when using an object tag. transforms are only applied to video tags to make up for object-fit support.

You can always set `stretching` to none in the config and apply it yourself, but then Flash will not stretch the way you want :(

```
stretching: "uniform", // setting this to "none" will prevent a transform scale from being set
aspectratio: "16:9",
width: "100%",
primary: "flash" // remove this
```

**Comment by donato** [comment]
@kharri1073 - if you have any other questions feel free to re-open this ticket
