### ISSUE TITLE
Delayed Seek in HTML5 provider

### ISSUE THREAD

**Issue by robwalch** [jwplayer/jwplayer#918]
Handling of seek commands before 'timeupdate' or 'canplay' events by setting a `_delayedSeek` time results in a lot of complexity in html5.js. This was made worse recently by having to add a video tag `play()` for Firefox to trigger the 'canplay' event we require after changing video src (#916).

We need to continue to simplify html5.js by removing individual properties or flags that introduce functionality in the provider that is meant to store desired state.

**Comment by coladeu** [comment]
Can you do a caption delay control feature? To control the subtitle delay if is out of sync?  Or can you tell me with what line of the code from jwplayer.js do i have to play in order to get an effect on caption delay?

**Comment by johnBartos** [comment]
@coladeu There is no feature for captions delay. When the HTML5 provider is active we're using the browser's native playback capabilities, and this includes native captioning. We can't modify the times of native captions because they exist outside of the player. When rendering non-natively, I suppose you could modify the start time immediately after parsing here (https://github.com/jwplayer/jwplayer/blob/master/src/js/controller/tracks-loader.js#L68) or when parsing, here (https://github.com/jwplayer/jwplayer/blob/master/src/js/parsers/captions/vttparser.js#L234). I'm not sure how well or if this will work at all, though.
