### ISSUE TITLE
Flash blocked error reported when autostart is false

### ISSUE THREAD

**Issue by mattcoz** [jwplayer/jwplayer#928]
I have videos that will play fine with autostart set to true, but when autostart is set to false it will report the flash plugin as being blocked. I've tested this in both Firefox and Chrome and get the same result. I can go into the developer tools, remove the jw-flag-flash-blocked class to show the controls, then press play and it plays fine.

7.1.4 (true): https://digital.sportingedge.com/video/streaming/TESTVIDEO/video.do
7.1.4 (false): https://digital.sportingedge.com/video/streaming/TESTVIDEO/video.do?autoplay=false
7.2.3 (true): https://digital.sportingedge.com:8443/video/streaming/TESTVIDEO/video.do
7.2.3 (false): https://digital.sportingedge.com:8443/video/streaming/TESTVIDEO/video.do?autoplay=false

**Comment by robwalch** [comment]
Does the version of jwplayer.flash.swf match the version of jwplayer.js?

**Comment by robwalch** [comment]
ActionScript needs to run on embed, but it cannot if you hide the swf. In your CSS, you're preventing Flash from setting up while the player is IDLE. This would also break replay functionality, because hiding and then showing the swf, or removing it and re-adding it to the DOM, causes the plugin to re-instantiate the Flash app.
```
#player.jw-state-idle .jw-swf {
    display: none !important;
}
```
Remove this CSS. It interferes with player functionality, and is the cause of this issue.
